### ISSUE TITLE
2020 年のクリスマスシーズンに間に合うように、Advent Calendar 機能をぜひ！

### ISSUE THREAD

**Issue by msmhrt** [zenn-dev/zenn-roadmap#101]

**Comment by catnose99** [comment]
これはやる必要がありそうなので、がんばって間に合わせます！

**Comment by msmhrt** [comment]
ありがとうございます。期待しています！

**Comment by msmhrt** [comment]
もしも、シーズン合わせの開発が負担になって、本来優先順位が高いはずだったチケットが後回しになったり、サービスの品質が低下したりしてしまったら本末転倒だと思いますので、どうか無理のない範囲でお願いします。

気温も大分下がって来ましたので、くれぐれもご自愛ください。

**Comment by catnose99** [comment]
たしかに他に優先順位が高いものが出てくる可能性があるので、まだ不確実な部分が大きいです。
お気遣い感謝します。ありがとうございます！

**Comment by catnose99** [comment]
期待していただいた方、すみません。
実際は↓こんな理由で今年はやめておきました。

https://twitter.com/catnose99/status/1334337286645841922

また、今のフェーズではイベントでユーザーを一気に集めるより、ユーザーからサービス自体を評価してもらえるように改善を加えていきたいと思っています。

来年どうするかはじっくり考えようと思います。
