### ISSUE TITLE
書いた記事の編集時に、Ctrl+zを押すと記事の内容が消える

### ISSUE THREAD

**Issue by fagai** [zenn-dev/zenn-roadmap#102]
書いた記事を編集する際に、最初に`Ctrl+z`を押すと記事の内容が消えます。(加筆した後に何度か`Ctrl+z`で戻っても同様のことが起きます)
保存せずに終了すれば内容は戻ってきますが少し驚いてしまうので解決すると嬉しいです。

**Comment by catnose99** [comment]
なるほど。ご確認いただきたいのですが
https://easymde.tk/
👆こちらのデモでも同じ現象は発生しますか？

**Comment by fagai** [comment]
あー起きますね・・・。
ライブラリ依存でしょうか

**Comment by fagai** [comment]
ちなみにもう一個親のSimpleMDEのDemoでは起きなかったですね

**Comment by catnose99** [comment]
ありがとうございます。ライブラリ依存の可能性が高いですね…。
ちょっと調べてみます。

**Comment by catnose99** [comment]
こちらパッチを当てられないか試してみましたがちょっと難しそうなので、申し訳ないのですが新しいエディターへの切り替えまでお待ちください。
※ 新エディターでは該当の問題は発生しないはずです
