### ISSUE TITLE
Table中の改行に対応してほしい

### ISSUE THREAD

**Issue by sogaoh** [zenn-dev/zenn-roadmap#104]
Table中で意図的に改行を入れたいケースがあるのですが、 <br> タグ（その他タグ全般的にダメな仕様なのは承知してます）が許容されていないためそれができません。

https://zenn.dev/zenn/articles/markdown-guide

を見ましたが対応していないように思われるので要望として issue を上げてみます。
ご検討よろしくお願いします。

**Comment by sogaoh** [comment]
以下の記事が実際に症状(?)が出ているものです
https://zenn.dev/sogaoh/articles/2020_02_11_08_37-from-qrunch
https://zenn.dev/sogaoh/articles/2020_02_16_23_29-from-qrunch

**Comment by manabian-** [comment]
私のマークダウンでの記載方法として、表の中で改行したいときに<br>をいれるのですが、改行されませんでした。

本対応していただけると、助かります。

**Comment by catnose99** [comment]
メモ
- markdown-it には[安全なHTMLタグの使用だけを許可するような仕様はない](https://github.com/markdown-it/markdown-it/issues/620)
- markdown-it-br というパッケージもあるが、メンテされておらず、何か問題が発生して対応が必要になったときにforkして管理するには少し辛い実装（というかそうならざるを得ない）
- やるならmarkdown-it自体ではタグをそのまま通して、HTMLへの変換後に[sanitize-html](https://www.npmjs.com/package/sanitize-html)などでサニタイズを行うという形

**Comment by lotz84** [comment]
推奨されるやり方かは分かりませんが、workaroundとして数式を経由すればテーブルの中でも改行できるようです。

```
|a|b|
|:----|:----|
|c|こんな風に $\\$ 改行ができます|
```

![](https://user-images.githubusercontent.com/7668186/103076688-a6b1f180-4611-11eb-98d6-9c6f425411db.png)

**Comment by catnose99** [comment]
@lotz84 すごい、このworkaroundは気づかなかったです。

brタグのサポートはつい最近取り組んでいた部分で、もうすぐリリースできると思います。

https://github.com/zenn-dev/zenn-editor/commit/f52b4a1977433a9dc76920d9c3d63b732e8d7c99

**Comment by catnose99** [comment]
@sogaoh 
@manabian- 
@lotz84 
`<br>`で改行できるようになりました。遅くなってしまいすみません。
