### ISSUE TITLE
.tfファイルがリンクと認識されないようにしてほしい

### ISSUE THREAD

**Issue by sogaoh** [zenn-dev/zenn-roadmap#105]
.tf ファイル（Terraform設定ファイルでだいたい使っています）が、見出しにあると
ファイル名だけでも HTML に変換される過程で `<a href="http://` が付いてしまいます。

執筆者の意図しない挙動であるように思うので、付かないようにしてほしいです。

**Comment by catnose99** [comment]
現状だと\`◯◯.tf\`のようにインラインのコードとして書いていただく必要がありそうです。

**Comment by sogaoh** [comment]
コメントありがとうございます。ちょうどそうしてました。

**Comment by sogaoh** [comment]
見出しじゃなくてもリンクと認識されるのを確認したのでタイトルを変更しました

**Comment by catnose99** [comment]
時間ができたときに確認してみます

**Comment by catnose99** [comment]
@sogaoh 
こちら修正されました！
https://github.com/zenn-dev/zenn-editor/pull/49

**Comment by sogaoh** [comment]
ありがとうございます。後ほど（今夜かも）確認します。

**Comment by sogaoh** [comment]
https://zenn.dev/sogaoh/articles/20-10-17-f3750a76ca19603736cd の記事をアップデートしてみて期待結果（.tfファイルがそれだけでリンクにはならない）が得られることを確認できました。ありがとうございました。

**Comment by catnose99** [comment]
丁寧にありがとうございます！
