### ISSUE TITLE
🔔アイコンに新着バッジがほしい

### ISSUE THREAD

**Issue by obata15** [zenn-dev/zenn-roadmap#106]
ずっと「投稿したのにLikeがもらえない…」と思っていたので。

**Comment by catnose99** [comment]
あれ、Likeがつくとこんなか感じでバッジが表示されるのですが、表示されていないですか？？
<img width="304" alt="スクリーンショット 2020-10-03 16 44 26" src="https://user-images.githubusercontent.com/34590683/94986202-baf8cc00-0597-11eb-965d-e30f64ba0268.png">

**Comment by obata15** [comment]
@catnose99 
macOS CatalinaのEdgeとWindows10のEdgeとAndroid 11のEdgeを利用しているのですが、たぶん表示されたことがないですね…
今までに17個ほどLikeをもらっているので、新着があるタイミングは何度かあったはずですが…
少し他のブラウザなどでも見つつ検証したいと思います

**Comment by catnose99** [comment]
@obata15 
今確認したらちょっとしたミスがありました…！すみません！！
すぐに修正してデプロイします！

**Comment by catnose99** [comment]
@obata15 こちら対応しました！気づくのが遅くなってしまい、すみませんでした。

**Comment by obata15** [comment]
@catnose99 
ありがとうございます。
次にLikeがついた時に確認させていただきます🙏

**Comment by obata15** [comment]
@catnose99 
バッジがつくのを確認できました。
対応ありがとうございました🙏

**Comment by catnose99** [comment]
@obata15 こちらこそありがとうございました！
