### ISSUE TITLE
アカウント作成を中断できない

### ISSUE THREAD

**Issue by anatawa12** [zenn-dev/zenn-roadmap#107]
アカウントを作成する際に、googleアカウントの選択を誤ったなど、アカウント作成を中断し、再度始めたくなりました。
しかし「まずは名前を決めましょう」と書かれたページ( https://zenn.dev/onboarding )にはキャンセルするためのボタンはなく、zenn.devのトップ、 https://zenn.dev/enter などからリダイレクトされるため、中断することができませんでした。
https://zenn.dev/onboarding の方でアカウント作成を中断できるようにしていただきたいです。

[(こちらでTwitterで報告したものと同一になります。)](https://twitter.com/kakerigawa/status/1312347877159526400?s=21)

**Workaround**
ブラウザのCookieを削除すると上記のをリダイレクトがなくなり、再度作成できるようになります。

**Comment by catnose99** [comment]
onboardingページに「登録を中断する」というボタンを設置しました。

**Comment by ensan-hcl** [comment]
こんにちは。現在「登録を中断する」というボタンを押すと「エラーが発生しました」と表示され、中断ができない状態になっています。ご確認頂けると幸いです。
環境はChrome OSのChrome、バージョンは104.0.5112.83です。

**Comment by cm-wada-yusuke** [comment]
@ensan-hcl こちら原因がわかりまして、ただいま修正リリースを準備しています。お手数をおかけしますがしばらくお待ち下さい。お急ぎの場合、`https://zenn.dev/` のCookie を削除いただくことで登録画面は表示されなくなります。

**Comment by cm-igarashi-ryosuke** [comment]
@ensan-hcl さきほど修正リリースが完了しました。お手数をおかけし申し訳ありませんでした。また、ご報告いただきありがとうございました。

**Comment by ensan-hcl** [comment]
ご対応ありがとうございます！助かりました！！
