### ISSUE TITLE
アカウント作成画面にてGoogleアカウントのアイコンも表示していただきたい

### ISSUE THREAD

**Issue by anatawa12** [zenn-dev/zenn-roadmap#108]
複数のGoogleアカウントがある際、あまり注意せずにアカウントを選択するとどちらのグーグルアカウントを選択したかが分かりづらいので、アカウントの名前を選択する画面でGoogleアカウントのアイコンを表示していただきたいです。

今でもニックネームのところにGoogleアカウントの名前が反映されるようですが、アイコンがあると判断しやすいため提案させていただきました。

**Comment by catnose99** [comment]
対応済み
