### ISSUE TITLE
売上でなく売れた冊数を知りたい

### ISSUE THREAD

**Issue by Jxck** [zenn-dev/zenn-roadmap#113]
現状では book の売上や article のサポートなどが全て混ざった合計金額しかわかりませんが、書籍ごとに売れた冊数がわかると嬉しいです。

**Comment by catnose99** [comment]
こちら販売ごとに集計を行っており、あとは表示するだけという状態なので近日中に対応します。

**Comment by catnose99** [comment]
最終的には日ごとの販売数なども見れるようにしたいのですが、とりあえずは本ごとの数量を表示する形になります

**Comment by Jxck** [comment]
良いと思います！ > 本ごとの数量
(逆に細かいデータやグラフが出すぎると過度に気を取られるので、累計冊数ぐらいが丁度いいかもですね)

**Comment by catnose99** [comment]
こちら対応しました！
<img width="419" alt="スクリーンショット 2020-10-07 18 30 03" src="https://user-images.githubusercontent.com/34590683/95313474-23fb7f00-08cb-11eb-8d4c-94ea89651c2a.png">
