### ISSUE TITLE
Feature Request: StackBlitzの埋め込み

### ISSUE THREAD

**Issue by lacolaco** [zenn-dev/zenn-roadmap#118]
現在サポートされているCodePenやJSFiddleに加えて、[StackBlitz](https://stackblitz.com/) の埋め込みに対応してもらえるとうれしいです。

**Comment by catnose99** [comment]
たしかにCodeSandboxに対応するならStackBlitzも対応するべきな気がしますね。
https://github.com/zenn-dev/zenn-roadmap/issues/6

Ellie（Elmのクラウド開発環境）の埋め込みの要望も以前にいただいており、要望にすべてに対応していくと無限に増えそうなので、どこかで対応基準を決めようと思います。おそらくそのサービスのユーザー数等になってしまうと思いますが…

**Comment by lacolaco** [comment]
なぜStackBlitzの埋め込みを希望するかというと、Angular開発者コミュニティでの利用が盛んだからです。
StackBlitzはAngularの公式ドキュメンテーション内でサンプルコードのLive Exampleとして利用されていて、その影響でユーザーがかんたんなデモアプリやサンプル実装を共有し合うのにStackBlitzがよく使われています。
もしZennにStackBlitzが埋め込みできれば、Angular開発者がノウハウを共有しやすくなうのではないかと思っています。

私自身もGitbookで執筆しているAngularの本をZennに移したいと考えたのですがStackBlitzがブロッカーとなっています。

**Comment by catnose99** [comment]
詳細をありがとうございます。
CodeSandboxと合わせて対応する予定です。今しばらくお待ちください。

**Comment by catnose99** [comment]
@lacolaco 
対応しました。
CLIを使っている場合は`npm install zenn-cli@latest`などで最新版にアップデートしていただければと思います。

https://zenn.dev/zenn/articles/markdown-guide#zenn%E7%8B%AC%E8%87%AA%E3%81%AE%E8%A8%98%E6%B3%95

**Comment by lacolaco** [comment]
ありがとうございます！

**Comment by lacolaco** [comment]
@catnose99 zenn-cli `0.1.47`、オンラインエディタの両方で試してみたのですが、 `StackBlitzのembed用のURLを指定してください` と表示されるのみで埋め込みに失敗しているようです。
想定される埋め込み用URLは以下のフォーマットのものであっていますか？

https://stackblitz.com/edit/angular-i8x98w?embed=1&file=src/app/app.component.html

![image](https://user-images.githubusercontent.com/1529180/95757713-74674800-0ce2-11eb-93cc-cf130fe45cd5.png)

**Comment by catnose99** [comment]
@lacolaco 
すみません、StackBlitzの埋め込みのURLパターンを把握できていませんでした。
さきほど修正して新しいバージョンをリリースしました（`0.1.48`）。お手数ですがご確認よろしくおねがいします。
https://github.com/zenn-dev/zenn-editor/commit/691292ad2a2352363946caad9cd9027d34540701

**Comment by lacolaco** [comment]
0.1.48にて動作確認できました！対応ありがとうございます！

**Comment by catnose99** [comment]
早速ありがとうございます！
