### ISSUE TITLE
プレビューのコードが崩れることがある

### ISSUE THREAD

**Issue by skanehira** [zenn-dev/zenn-roadmap#120]
## 概要
プレビュー中のコードブロックが崩れることがあります。

- プレビュー画面
  ![image](https://user-images.githubusercontent.com/7888591/95649330-f22b2800-0b17-11eb-9777-01e37adfb7db.png)

- 記事の画面
  ![image](https://user-images.githubusercontent.com/7888591/95649343-0a02ac00-0b18-11eb-9694-eddb739a45dd.png)

## 環境
- OS
  Ubuntu 18/04 LTS
- Browser
  Vivaldi 3.3.2022.47/ Chrome バージョン: 85.0.4183.121

**Comment by catnose99** [comment]
@skanehira ご報告ありがとうございます。
このプレビューはZenn CLIで表示したときのものでしょうか？
さきほどちょうどソースコードのフォント周りの変更を行ったため、`npm install zenn-cli@latest`を実行してみていただけますか？（`npx zenn -v`を実行したときに`v0.1.45`となっていれば2020/10/10 17:00時点の最新版です）

ご確認よろしくお願いします。

**Comment by skanehira** [comment]
治りました！
フォントも見やすくなっていますね

ありがとうございます！
