### ISSUE TITLE
diffのハイライトが正しく表示されない

### ISSUE THREAD

**Issue by softoika** [zenn-dev/zenn-roadmap#123]
以下のコードブロックで+の差分も-の差分と同じ色でハイライトされてしまいます。

![image](https://user-images.githubusercontent.com/25437304/95670743-19dac880-0bca-11eb-8731-4cbcdaec578a.png)
![image](https://user-images.githubusercontent.com/25437304/95670733-f6178280-0bc9-11eb-8c84-1dbaa367214e.png)

**Comment by catnose99** [comment]
確認します！

**Comment by catnose99** [comment]
おそらくprism.jsのプラグインを入れる必要あり

**Comment by catnose99** [comment]
@softoika 
CSSの当て方に誤りがありました。さきほど修正を行いました。
CLIを使用されている場合はお手数をおかけして申し訳ないのですが、`npm install zenn-cli@latest`でアップデートをお願いします。
