### ISSUE TITLE
本のレビュー機能

### ISSUE THREAD

**Issue by catnose99** [zenn-dev/zenn-roadmap#124]
著者がON/OFFを切り替えられるようにするべきかどうか

**Comment by konojunya** [comment]
これがそのものかどうかわからないですが、本を書く際に社内の有識者にレビューをもらってから出したいみたいなケースがあり、ちょうどQiitaの限定公開みたいな機能があると嬉しいなぁと思いました🙏

**Comment by catnose99** [comment]
ひとまずはスクラップで代替する方向で考える
