### ISSUE TITLE
[機能要望] 公開日を絶対日時で表示して欲しい

### ISSUE THREAD

**Issue by Jxck** [zenn-dev/zenn-roadmap#125]
更新のない記事は日時の表示が相対日時になっていますが、技術記事などはなるべく「いつかかれたのか」をぱっと知りたいので、日時で表示してほしいです。

![image](https://user-images.githubusercontent.com/322289/95682629-3ce49700-0c21-11eb-882c-9788dc08b8de.png)

更新があった日はツールチップが出るので、それでも良いと思います。

![image](https://user-images.githubusercontent.com/322289/95682688-98af2000-0c21-11eb-98ae-f593e8616064.png)

**Comment by catnose99** [comment]
たしかに今の形だと「◯◯が2020年5月に仕様変更されたが、それより前に書かれたどうか」のようなことが知りたいシーンで分かりづらいですね。トップページ等の記事へのリンクでは現在の相対日時を維持しつつ、記事ページでは日付表示にしようと思います。

**Comment by catnose99** [comment]
対応しました
