### ISSUE TITLE
【機能要望】ページ内リンクを作成できるようにしてほしい

### ISSUE THREAD

**Issue by Midoliy** [zenn-dev/zenn-roadmap#126]
現状、Book作成において目次を作成できない都合でチャプタートップにページ内リンクを利用した目次を作成しようと思ったのですが、markdown形式でもhtml形式でも作成できないようなので、ページ内リンクが作成できる機能が欲しいです。

どういった形式でも問題ないのですが、たとえばmarkdown形式であれば

```
[○ H1 タイトル1](#-○-H1-タイトル1)
[　◇ H2 サブタイトル1](#-◇-H2-サブタイトル1)
[　　▽ H3 項目1](#-▽-H3-項目1)


# ○ H1 タイトル1

## ◇ H2 サブタイトル1

### ▽ H3 項目1
```

のような形でスペースをハイフンなどで埋めるような形や、html形式であれば、

```
[○ H1 タイトル](#H1タイトル1)
[　◇ H2 サブタイトル1](#H2サブタイトル1)
[　　▽ H3 項目1](#H3項目1)

<a id="H1タイトル1"></a>
# ○ H1 タイトル1

<a id="H2サブタイトル1"></a>
## ◇ H2 サブタイトル1

<a id="H3項目1"></a>
### ▽ H3 項目1
```

のような形を想定しています。

**Comment by catnose99** [comment]
なるほど、できないか確認してみます。

**Comment by Midoliy** [comment]
一応開発ツールのところからidをコピペで持ってくればできなくはないのですが、手間なのと%エンコードされている都合上メンテナンス性が非常に悪くなるので、対応いただけると嬉しいです。

**Comment by catnose99** [comment]
そうですよね。
本のページにも記事と同じように自動で目次（h1とh2見出しまで含める）を挿入する形であればシステムの都合上対応がしやすいと思われます。

イメージしているのは
・チャプターをビューアーで表示したときに、タイトルの下のあたりに目次を挿入する
・目次を表示するかどうかは本の設定で選べるようにする（cliを使っている場合`toc: true`とかですかね…）
という感じです。
何か意見があれば教えていただければありがたいです。

**Comment by Midoliy** [comment]
目次を出す位置としてはタイトルの下あたりで問題ないと思います。
ただ、目次としたい要素の深さについては `depth: h3` や `depth: ###` などのように指定できるとより良いように思います。

これは `本` という立ち位置であるので記事よりもより詳細な目次を提供したいニーズが高いと思うからです。
ex) TIPS や 備考 など'

また、階層構造が視覚的によりわかりやすい表示形式となると嬉しいです。

**Comment by catnose99** [comment]
あー、なるほどですね。
ありがとうございます。いただいた情報を参考に考えてみます。

**Comment by catnose99** [comment]
@Midoliy 

チャプターごとに目次を表示できるようになりました。デフォルトでは「h1」と「h2」見出しまで目次に表示されます。

`config.yaml`で`toc_depth: 0`と記載すると目次を非表示にできます。`toc_depth: 1`とすると「h1」見出しだけが目次に表示されます。現在、この値は`0`〜`3`の範囲で指定する必要があります。

※ この値は本全体での設定になります。チャプターごとに別々の設定をすることはできません。
