### ISSUE TITLE
記事の公開日時を時刻まで含むかたちでtime要素で妥当にマークアップしてほしい

### ISSUE THREAD

**Issue by aereal** [zenn-dev/zenn-roadmap#127]
2つの要望を1つのissueに含めるのは望ましくないと思いますが、分かち難いと感じたので併記させてください。

# 妥当なマークアップにしてほしい

現在、記事の公開日時のマークアップは `<time>2020/10/13</time>` のようになっています。

time要素は子孫のテキストノードかdatetime属性に[妥当な日時文字列](https://html.spec.whatwg.org/multipage/text-level-semantics.html#datetime-value)を持たなければいけません。
そして `2020/10/13` のような `YYYY/mm/dd` 形式は妥当な日時文字列ではありません。

もしこのマークアップが改善された場合、time要素の `dateTime` 属性か `textContent` 属性をパースして閲覧者が機械的に加工しやすくなります。
たとえば相対表記を望む場合は現在時刻との差分を計算して表示することができるでしょう。

# 時刻を含めてほしい

妥当なマークアップに改善し機械可読性を上げたうえで、記事の公開日時を時刻まで含めてマークアップしてほしいです。

公開されてから日が浅い記事は日付のみの表記だとどれくらい新鮮か判断が難しいです。

表示上は日付のままでも構いませんのでdatetime属性では時刻まで含めてもらえるととても嬉しいです。

**Comment by catnose99** [comment]
丁寧なご指摘、ありがとうございます。
こちら後でやろうと思ってすっかり忘れていました。

ただいま対応しました。ご報告ありがとうございました。
