### ISSUE TITLE
タブ選択のブラウザバック対応

### ISSUE THREAD

**Issue by konojunya** [zenn-dev/zenn-roadmap#133]
Zenn内の沢山のタブはStateによって変えられている気がしますが現状ブラウザバックした時にそのタブの選択状態を保持できていないため記事を読むのに少し煩わしさを感じます。

例えばnew!のタブを押下→気になる記事が2つ並んでいた→1つ目の記事を読む→ブラウザバックする→Trendのタブに戻ってしまう

この場合、new!をまた押してさっき読んでた記事までスクロールしてその次に気になる記事を読む。みたいな行動をせねばならず少し手間です(またtopicsなんかは横にスクロールがあり長いのでより煩わしい)

方法はお任せしますが、urlのqueryに入れてもらえるとそのページでブックマークなども行えて嬉しいです。

**Comment by catnose99** [comment]
これは自分でも同じようなストレスを感じていたので修正します。

※ tech/idea/bookのそれぞれで別々にクエリを振ると複雑になりそうだと思い、後回しにしていました。ひとまず、3つのタブの位置を同期することにします。トピックのフォロー機能がついたらトップページの構成自体を変えてもうちょっと良さげにします。

**Comment by catnose99** [comment]
@konojunya 対応しました！
