### ISSUE TITLE
【機能要望】Bookで大見出しだけなく、中・小見出しのインデックスがほしい

### ISSUE THREAD

**Issue by j5ik2o** [zenn-dev/zenn-roadmap#134]
大見出しの目次だけでは読みにくいと感じる時があります。ページの先頭などに中・小見出しレベルの目次を作れないでしょうか。

**Comment by catnose99** [comment]
ありがとうございます。
こちらと同じようなイメージでしょうか。
https://github.com/zenn-dev/zenn-roadmap/issues/126

**Comment by j5ik2o** [comment]
@catnose99 はい。同じだと思います。重複ということでクローズしてもらってOKです。

**Comment by catnose99** [comment]
ありがとうございます。
対応予定ですので、しばらくお待ちください。

Duplicate of #126

**Comment by catnose99** [comment]
@j5ik2o 
こちら対応しました。
https://github.com/zenn-dev/zenn-roadmap/issues/126#issuecomment-716281354
