### ISSUE TITLE
Dockerfileのシンタックスハイライトを使えるようにしてほしい

### ISSUE THREAD

**Issue by inductor** [zenn-dev/zenn-roadmap#137]
スクリーンショットのとおり、現状の画面だとDockerfileのシンタックスハイライトが効いていないので、使えるようにしてほしいです。

![image](https://user-images.githubusercontent.com/20236173/96976044-4db4d700-1556-11eb-95d4-bf0701f54a7b.png)

```Dockerfile
FROM ubuntu
ENV name value # 非推奨
ENV name=value # 今後はこっちを使いましょう
CMD ["echo", "$name"]
```

**Comment by catnose99** [comment]
ZennのシンタックスハイライトにはPrism.jsを使用しています。
↓ 対応言語一覧
https://prismjs.com/#supported-languages

「dockerfile」のように先頭を小文字にするとハイライトが効くようです。

※ [マークダウンガイド](https://zenn.dev/zenn/articles/markdown-guide)にも対応言語一覧へのリンクを載せるようにしました。

**Comment by inductor** [comment]
あー。ケースセンシティブなんですね。。。ありがとうございます！

**Comment by catnose99** [comment]
言われてみれば自動でlowercaseに変換できますね。今度改善します。
https://github.com/zenn-dev/zenn-editor/issues/53

**Comment by catnose99** [comment]
@inductor 
先頭が大文字でもハイライトされるように修正しました。
CLIを使っている場合は`npm install zenn-cli@latest`で更新をお願いします（v0.1.51にて対応）。
