### ISSUE TITLE
閲覧数を表示できるようにしてほしい

### ISSUE THREAD

**Issue by marnysan111** [zenn-dev/zenn-roadmap#138]
閲覧数を表示できるようにしてほしいです。記事を書いている中で、モチベーションにつながる理由の一つに、「閲覧数」があります。(個人的に)

沢山の人に見られてるうへへ～みたいに思いたいので、実装お願いします

**Comment by catnose99** [comment]
そうですよね。PV自体はこれまでの記事を含めて取っているのでアップデートで対応します！
しばらくお待ちください。

**Comment by catnose99** [comment]
重複しているため、こちらはクローズします。
duplicate of #98
