### ISSUE TITLE
[要望] fish-shellのシンタックスハイライト

### ISSUE THREAD

**Issue by skanehira** [zenn-dev/zenn-roadmap#139]
現在fish-shellのシンタックスハイライトができないので、できるようにしてほしいという要望です

![image](https://user-images.githubusercontent.com/7888591/97104074-3875af00-16f4-11eb-82e9-0b5a5de4bc8d.png)

**Comment by catnose99** [comment]
シンタックスハイライトにはPrism.jsを使っており、対応言語は下記ページの通りになります。
https://prismjs.com/#supported-languages

Prism.jsがサポートしていない言語の対応はしばらく先になりそうです。すみません🙏

現時点では`fish:filename.fish`ではなく`shell:filename.fish`のように`shell`を指定していただくのが良さそうです。

**Comment by catnose99** [comment]
> ```fish
> ```
と指定してもシンタックスハイライトが効くように暫定対応を行いました
