### ISSUE TITLE
モバイルブラウザで、記事の Topics を上部に表示して欲しい

### ISSUE THREAD

**Issue by msmhrt** [zenn-dev/zenn-roadmap#140]
私はスマートフォンで Twitter を閲覧していて、Zenn の記事タイトルを見て興味を持ち、リンクを辿ってモバイルブラウザで閲覧するようなことが良くあるのですが、記事によってはタイトルや冒頭だけではどの言語やフレームワークについて話なのかがよく分からないことがたまにあり、それを Topics で把握しようとしても記事中の Topics セクションが最下部より少し上にあるので、一度最下部までスクロールしてから上部にスクロールしつつ Topics セクションを探すのに少し手間取ることが何度かありました。

そこで改善要望なのですが、モバイルブラウザでの閲覧時に Topics の先頭トピックだけでも記事の上部に表示していただけると、「ああ、JavaScript についての記事なのね」等と把握がしやすくなりますので、検討していただけないでしょうか？

以上、どうかよろしくお願いいたします。

**Comment by catnose99** [comment]
ありがとうございます。
これは僕も実際に何度か経験しました。
改善しますのでしばらくお待ちください。

**Comment by catnose99** [comment]
@msmhrt 対応しました。

**Comment by msmhrt** [comment]
いい感じです。ありがとうございました。
