### ISSUE TITLE
埋め込み YouTube 動画の再生後の関連動画を改善して欲しい

### ISSUE THREAD

**Issue by msmhrt** [zenn-dev/zenn-roadmap#143]
それ程困っている訳ではないのですが、改善の要望が一点あります。

デスクトップ版の Web ブラウザで ```@[youtube](????????)``` で埋め込まれた YouTube 動画を含む記事を表示すると、再生終了後に関連動画を表示するのですが、現状の Zenn はその際に関連動画として YouTube にログイン中のアカウントの履歴も反映してしまうようになっているので、人によっては色々アレゲな動画が表示されてしまいます。

再生終了後に関連動画が表示されることは止められないので、

1. Twitter の埋め込み YouTube 動画のようにループ再生し続けるようにする
2. 「[YouTube 埋め込みプレーヤーとプレーヤーのパラメータ  |  YouTube IFrame Player API](https://developers.google.com/youtube/player_parameters?hl=ja#rel)」の説明通りに、```iframe``` 要素の ```src``` 属性の末尾に ```?rel=0``` を追加することで、関連動画に再生した動画と同じチャンネルか内の動画しか表示されないようにする

等の方法を検討してみていただけないでしょうか？

以上、どうかよろしくお願いいたします。

**Comment by catnose99** [comment]
あー、なるほどですね。
ループするように変更します。
ご指摘ありがとうございます。

**Comment by catnose99** [comment]
リリース待ち
https://github.com/zenn-dev/zenn-editor/commit/f7c712e240905a1cb857a217b0974ab7bdd678d4

**Comment by catnose99** [comment]
@msmhrt 対応しました。今後投稿or更新した記事に関しては関連動画が表示されなくなります。
