### ISSUE TITLE
先頭が絵文字の行で改行が反映されない

### ISSUE THREAD

**Issue by catnose99** [zenn-dev/zenn-roadmap#145]
https://zenn.dev/zenn/articles/markdown-guide#comment-5c9050ee9b527e0173a3

## 確認が必要そうな点
- [ ] ブラウザのエディター上で発生している問題か、CLIのプレビュー上で発生している問題か

## ブラウザ上で問題が発生している場合
- [ ] 使用環境（OS/使用ブラウザ）など
- [ ] 記事（記事を作成してプレビューした場合）でも同様の問題が発生するか
- [ ] 2つ以上改行を入れても、改行が反映されないか
- [ ] マークダウン変換のAPIのレスポンスがどうなっているか

例えば
```
A
B
C

D
```
をプレビューしたときの、HTMLの変換APIからのレスポンスが
```
{"html":"<p>A<br>\nB<br>\nC</p>\n<p>D</p>\n"}              
```
となっていなければ変換に問題がある

**Comment by freeonterminate** [comment]
原因がわかりました。
行の先頭が絵文字の場合です。
例えば
```
😫
😫
😫
```

は
```
😫😫😫
```
となります。

**Comment by freeonterminate** [comment]
一応、上記の問いにも答えておきます。

## 確認が必要そうな点
### ブラウザのエディター上で発生している問題か、CLIのプレビュー上で発生している問題か
ブラウザのエディタです。

## ブラウザ上で問題が発生している場合
* **使用環境（OS/使用ブラウザ）など**
OS: Windows 10 Pro 1909
Browser: SRWare Iron, New Edge (確認用)

* **記事（記事を作成してプレビューした場合）でも同様の問題が発生するか**
発生しました。

* **2つ以上改行を入れても、改行が反映されないか**
2つ以上改行を入れると 2つとも反映されます。

* **マークダウン変換のAPIのレスポンスがどうなっているか**
Chrome の Developer Tool でみていたのですが、API のレスポンスを確認する方法がわかりませんでした…

**Comment by catnose99** [comment]
@freeonterminate 
あー、そういうことですね！
詳しくありがとうございます。

確認したうえで対応します！

**Comment by catnose99** [comment]
おそらく修正済み
