### ISSUE TITLE
[要望] 記事編集時に公開済の記事とのDiffが見られる機能が欲しい

### ISSUE THREAD

**Issue by nekocodeX** [zenn-dev/zenn-roadmap#150]
## 概要
- 記事の編集画面で、プレビュー時に公開済の記事とどこが変わったのか見られる機能
    (GitHubのPreview changes機能のようなもの)

    ![e.g.](https://user-images.githubusercontent.com/65624234/97818060-83d72100-1ce3-11eb-82c0-31c829d9ed81.png)

## なぜ必要か
- 公開済記事を編集する際に、一部だけを変更して表記ゆれ等が生じてしまわないように事前チェックできる

    …など

**Comment by catnose99** [comment]
丁寧にありがとうございます。
GitHubリポジトリ連携をお試しいただけますか？
Diffだけでなく変更履歴が残りますし、執筆・公開体験もウェブ上のエディターを使うより良いかもしれません。
https://zenn.dev/zenn/articles/connect-to-github

よろしくお願いします。

**Comment by nekocodeX** [comment]
ご返信いただき、ありがとうございます。

GitHubリポジトリ連携機能は存じておりました。
上記機能は試してみたいと考えております。

ですが、Webエディタ側にもあれば良いなと思い、Issueを立てさせていただいた次第です。
可能であれば、機能追加をご検討いただきたく存じます。

よろしくお願いいたします。

**Comment by catnose99** [comment]
なるほど！
こちらの都合で恐縮なのですが、できる限りアプリをシンプルにしてメンテナンスしやすくしたいという思いがあり…
Web上のDiff機能は実装が可能であっても、メンテンナンスコストがかなり高そう（そしてうまくdiffを出せなかったときに書き手が混乱してしまう）ので、今のところやる予定はないです…
本当にすみません！

**Comment by nekocodeX** [comment]
承知いたしました！
では、こちらでクローズさせていただきますね。

今後ともよろしくお願いいたします。

**Comment by catnose99** [comment]
@nekocodeX 
すみません！
もちろんあった方がユーザー体験が良いとは思っているので、リソースに余裕が出来たタイミングで改めて検討します。
今後ともよろしくお願いします。
