### ISSUE TITLE
機能要望:githubのソースコードを埋め込み可能にしてほしい

### ISSUE THREAD

**Issue by zecl2** [zenn-dev/zenn-roadmap#155]
```
<script src="https://gist-it.appspot.com/(githubのコードのURL)"></script>
```

githubコードの埋め込み例。

**Comment by catnose99** [comment]
gistの埋め込みはやりたいと思ってます。
現状対応していない事情としては、Reactの中でscriptタグをそのまま埋め込むことができないためです。
（iframeでやることも可能なのですが、高さの調整が少しややこしくなったりします）
対応まで時間がかかるかもしれません。ご理解いただけると幸いです。

**Comment by zecl2** [comment]
ありがとうございます。
事情があってすぐには難しいということで承知しました。

**Comment by catnose99** [comment]
@zecl2 
こちら対応しました。下記のような形で埋め込みができます。


```
@[gist](gistのページのURL)
```
