### ISSUE TITLE
トピックページで並び順を変えた時のスクロール位置

### ISSUE THREAD

**Issue by rururux** [zenn-dev/zenn-roadmap#156]
Trending/Alltime/Latestを切り替えると、自動的にスクロール位置がページの一番上に変わりますが、
トピックを見る為に下にスクロールし直す必要があるので、気になります。
(特にスマホ版では、一番上からだとトピックがほとんど見えなくなってしまうので)
切替時のスクロール位置を一番上でなく「Articles」等の場所に変更して頂けたらと思います。

**Comment by catnose99** [comment]
対応します！

**Comment by catnose99** [comment]
対応しました。

**Comment by rururux** [comment]
お疲れ様です、ありがとうございます！
