### ISSUE TITLE
ブラウザのアドレスバーで「安全ではありません」と出る場合がある

### ISSUE THREAD

**Issue by skanehira** [zenn-dev/zenn-roadmap#158]
## 問題
以下のURLで「安全ではありません」と出ます。

https://zenn.dev/nobonobo/articles/e651c66a15aaed657d6e

![image](https://user-images.githubusercontent.com/7888591/98880160-76cbe600-24ca-11eb-8e1e-b6d0ff30928c.png)

トップページだと出ませんでした。
![image](https://user-images.githubusercontent.com/7888591/98880116-5f8cf880-24ca-11eb-810e-c0147b4b943e.png)

## 環境
ブラウザ：Vivalid

## 補足
Chromeだと「安全ではありません」は出ませんでした

**Comment by catnose99** [comment]
@skanehira 
詳細にありがとうございます。
確認したところ、カードリンクのファビコンの部分の画像がhttpで読み込まれてしまっていたようです。
（ファビコンの読み込みはhttpsにリダイレクトされますがSafariなどのブラウザでは、srcがhttp://となっている時点でmixcontentとしてエラーを表示するようです）

さきほど修正しました。完全に見落としていたため助かりました。
ありがとうございます！
