### ISSUE TITLE
[feature request] いわゆる 'alert' のようなもの

### ISSUE THREAD

**Issue by su8ru** [zenn-dev/zenn-roadmap#160]
```
:::info
this is alert area
:::
```

のような md 記法の、いわゆる alert のようなものがほしいです！

記事内でちょっとした注釈を加えたい場合、現状 `>` 引用 の利用が主な選択肢であり、あまり良い状態ではないと思います。

お手すきの際で構いませんので、実装をご検討ください！

（既出でしたらごめんなさい、そっと Close していただいて構いません‥＞＜）

### Colors

Bootstrap 準拠が一番わかりやすそうですね

- success
- danger
- warning
- info
- secondary

**Comment by catnose99** [comment]
こちらとは違うイメージでしょうか。

<img width="755" alt="スクリーンショット 2020-11-15 15 12 52" src="https://user-images.githubusercontent.com/34590683/99178300-113f5a00-2755-11eb-8e8a-7a59f00aa64a.png">

現在infoの追加は検討しています。

**Comment by catnose99** [comment]
@su8ru 
一旦クローズします

**Comment by su8ru** [comment]
わわわ、すみません、確認不足でした…！そちらで間違いないです。お手数おかけして申し訳ありません＞＜

info の追加も心待ちにしております！寒い季節ですのでお体にお気をつけください…！
