### ISSUE TITLE
Gayzoに貼ったgifが表示されない

### ISSUE THREAD

**Issue by skanehira** [zenn-dev/zenn-roadmap#162]
## 問題
https://zenn.dev/skanehira/articles/2020-11-16-go-vim-gyazo

こちらの記事を投稿しましたが、記事の画面では何故かGyazoに貼ったgifが表示されない状態です。
ちなみにウェブプレビュー画面も`zenn preview`もちゃんと表示されていました

こちらは記事の画面
<img src="https://user-images.githubusercontent.com/7888591/99224571-eb37b980-2829-11eb-815a-6d7bd0681d09.png" width=600/>

こちらはウェブのプレビュー画面
<img src="https://user-images.githubusercontent.com/7888591/99224621-04406a80-282a-11eb-91fe-93493ac04aed.png" width=600/>

ちなみに、gyazoにアップロードした画像(png)は普通に表示されていました
gifもGitHubのREADMEに使っているもので、そちらはGitHub上では正常に表示されています。

## 環境
|        |               |
|--------|---------------|
|OS      |Ubuntu20.04    |
|ブラウザ|Vivaldi、Chrome|

**Comment by skanehira** [comment]
取得した記事のHTML自体はプレビューも記事の画面も同じものなのを確認しました

```json
{"html":"<p>zenn.devやQiitaで記事を書いていると画像をアップロードしたくなることがあります。<br>\nそして、とても良いことにzenn.devやQiitaにはWebのエディタ上では<code>Ctrl(Cmd) + v</code>でクリップボードから画像をアップロードできる機能があります。</p>\n<p>しかし普段Vimで記事を書いている自分としては、やはりVimだけで完結したいという気持ちがあります。<br>\nクリップボードの画像をアップロードのために、わざわざWebのエディタを開きたくないし、わざわざファイルに書き出したくないです。</p>\n<p>しかし、zenn.devとQiitaは画像アップロードのAPIを公開していないので長らく諦めていましたが、<a href=\"https://gyazo.com\" rel=\"nofollow\">Gyazo</a>というサービスがあるのを知りました。<br>\nGyazoにはAPIがあるので、それをWebエディタと使えば同じことができると思い<a href=\"https://github.com/skanehira/gyazo.vim\" rel=\"nofollow\">gyazo.vim</a>というプラグインを作りました。</p>\n<p><img src=\"https://i.gyazo.com/2adcdcc57f144bd524bc29bd1affbe75.gif\" alt=\"\"></p>\n<p>やっていることはシンプルで<code>gyazo</code>のCLIを使ってAPIを叩いているだけです。URLが返ってくるのでそれをそのまま現在行に挿入させるだけで同じような動作を再現できます。</p>\n"}
```

**Comment by catnose99** [comment]
ありがとうございます。
対応します。

**Comment by catnose99** [comment]
メモ。

1.  Cloudinaryで下記のエラーが出ているが対処できないか確認

```
Maximum total number of pixels in all frames/pages is 100 Megapixels. Requested 172.67 Megapixels
```

**Comment by catnose99** [comment]
dev.toでもCloudinaryで画像をプロキシしているようで同じ問題が報告されている模様。
https://github.com/forem/forem/issues/5813

> nothing we can do about this on our end.
