### ISSUE TITLE
Scrapsをモバイルサイトから新規作成

### ISSUE THREAD

**Issue by itskihaga** [zenn-dev/zenn-roadmap#163]
モバイルからスクラップを新規作成できる導線が無い気がしました。
ふと思い立った時に書き始めたいスクラップの目的上、モバイルからの導線はかなりわかりやすい所に置いて欲しいです。

**Comment by catnose99** [comment]
現状ないですね。スクラップはモバイルから作ることもあると思うので対応します！

**Comment by catnose99** [comment]
対応しました。
ユーザーメニューの[スクラップの管理]の遷移先に[新規作成]ボタンを用意しました。

**Comment by itskihaga** [comment]
ご対応いただきありがとうございました！
