### ISSUE TITLE
Scrapsの投稿を cmd + Enter で行えるようにする

### ISSUE THREAD

**Issue by konojunya** [zenn-dev/zenn-roadmap#164]
Scrapsを投稿するのにもし可能ならeditorにfocusを当てたとこからスタートして、cmd + enterで投稿できるようになるとより投稿が捗ると感じました

**Comment by catnose99** [comment]
たしかにそうですね。

- `Ctrl` + `P`：プレビュー
- `Ctrl` + `Enter`：submit

の2つのショートカットはやりたいと思います。

**Comment by catnose99** [comment]
プレビューはちょっと後回し・・・

**Comment by catnose99** [comment]
Ctrl + Enterでの送信に対応しました。
