### ISSUE TITLE
Windows上のFirefoxでコメント欄やScrapsに全角空白等が入力できない

### ISSUE THREAD

**Issue by okuoku** [zenn-dev/zenn-roadmap#165]
Windows 10 `1909` + Firefox `83.0` で、コメント欄やScrapsのMarkdown入力欄にWindows IMEを使用して全角空白が入力できません。Google Chromeは正常なようです。また、通常の記事入力画面はFirefoxでも正常なようです。

一般には、直接入力によって確定した内容が正常に入力されません。例えば、CorvusSKKのようなpreeditに余分な文字を含むIMEでは、preeditがそのまま入力されてしまいます。Windows IMEでは殆どの約物は一旦preeditを経由するため、影響を受ける入力は全角空白程度です。

CorvusSKKで"未来"と入力したところ:
![cap6](https://user-images.githubusercontent.com/100813/99882902-090c8080-2c67-11eb-8183-037bce2a3bf2.gif)

ChromeとFirefoxでCompositionイベントの内容に差異は無いため、同時に発生している他のDOMイベントに起因するかもしれません。

上記の入力のイベントログ:
https://codepen.io/okuoku/pen/qBNzova
![image](https://user-images.githubusercontent.com/100813/99883453-ec724780-2c6a-11eb-8bd5-d23e6adda76e.png)

**Comment by catnose99** [comment]
詳細にありがとうございます！
確認してみます。

**Comment by catnose99** [comment]
おそらく原因が分かりました。すみませんが、もうしばらくお待ちください。

**Comment by catnose99** [comment]
@okuoku 
こちらおそらく修正できたと思うのですが、よろしければご確認お願いします。

**Comment by okuoku** [comment]
[バッチリです](https://zenn.dev/okuoku/scraps/6b759ea7abd1f32d83ee) 👏👏

**Comment by catnose99** [comment]
早速ご確認いただき、ありがとうございますー！！！

**Comment by catnose99** [comment]
分かりやすくご報告いただきまして、ありがとうございました。

**Comment by okuoku** [comment]
[cc](https://twitter.com/blackenedgold/status/1330533083531993090) @keens
