### ISSUE TITLE
数式$$の直後にリンク[なにか](httpで始まる文字列)を書くとPreviewとPublicで数式が変換されない（Chrome）

### ISSUE THREAD

**Issue by wsuzume** [zenn-dev/zenn-roadmap#168]
`$a,b,c$は[ほげ](http)を参照。`　⇒ 変換されない

`$a,b,c$は[ほげ](http://hoge.fuga)を参照。`　⇒ 変換されない

`$a,b,c$は[ほげ](shttp)を参照。`　⇒ 変換される

`$a,b,c$は[ほげ](https)を参照。`　⇒ 変換されない

`$a,b,c$は[ほげ](hoge.fuga)を参照。`　⇒ 変換される

ブラウザ：Google Chrome 86.0.4240.193 (Official Build) (x86_64)
OS：macOS Catalina ver 10.15.7

**Comment by catnose99** [comment]
ありがとうございます、確認します。

念のため確認させていただきたいのですが、挙げていただいた中で困るのは
```
$a,b,c$は[ほげ](http://hoge.fuga)を参照。
```
ですよね、おそらく。

`$a,b,c$は[ほげ](shttp)を参照`みたいな書き方は基本的にすることはないですよね…？

**Comment by wsuzume** [comment]
ご対応いただきありがとうございます。

>念のため確認させていただきたいのですが、挙げていただいた中で困るのは
>`$a,b,c$は[ほげ](http://hoge.fuga)を参照。`
>ですよね、おそらく。

はい。まったく同じ記号法を別の記事内で用いていたので、他記事へリンクした際に起こりました。
軽微な問題ですが一応ご報告させていただきました。

**Comment by catnose99** [comment]
ありがとうございます。
心当たりがあって、多分こちらのissueに対応したときに生じた問題です。
https://github.com/zenn-dev/zenn-editor/issues/36#issuecomment-703213570

数日中に対応できると思うので今しばらくお待ちください。

**Comment by catnose99** [comment]
@wsuzume 
対応しました。ご不便をおかけしてすみませんでした。

もしzenn-cliを使っている場合は` npm install zenn-cli@latest`で更新をお願いします。

**Comment by catnose99** [comment]
あ、すでに保存されている投稿に修正を反映するためには再保存をする必要があります…！すみません！

**Comment by wsuzume** [comment]
@catnose99 
迅速にご対応いただきありがとうございました！

**Comment by catnose99** [comment]
いえ、ご迷惑をおかけしました。
いつも記事や本の更新を楽しみにしています！
