### ISSUE TITLE
ページ遷移時にGoogle AnalyticsでPVが記録されない

### ISSUE THREAD

**Issue by obata15** [zenn-dev/zenn-roadmap#169]
Google AnalyticsのG-から始まるデータストリームのトラッキングIDを設定したところ、リロード時にはPVが記録されるものの、通常のページ遷移の場合にPVが記録されないようです。
24時間ほど前にトラッキングIDを設定した後、PV数がほぼゼロなのを不審に思い、Google Analyticsのリアルタイムの概要ページを見ながら自分のブラウザでいくつかページを開いてみたところWindows 10のEdge, Chrome, FirefoxとmacOS Big SurのEdge, Chrome, Firefox, Safariの全てで再現しました。

データストリームのトラッキングIDを設定するのが初めてのため、もしかするとGoogle Analytics側の設定を間違えているかもしれないので、他の方の状況も知りたいです。

**Comment by catnose99** [comment]
丁寧にありがとうございます。

私の環境で試してみたのですが、リアルタイム計測が不安定なようで、そもそも分かりづらいのですが、リロードせずに他ページから遷移したページも一応計測されているようです。

ただ、Analyticsへの反映が遅かったり、ときどき反映されなかったりします。
（ブラウザのタブが非活性になっていると計測されないとかあるんですかね…）

もしかすると…ですが、ページのデータがキャッシュされている可能性があります。
Google AnalyticsのトラッキングIDを設定してから一度以上そのページを訪れるまでは、トラッキングIDの設定が行われていない状態のページデータが表示されることがあります。

ちなみにやっていることとしては、gtagの仕様に則って、以下を読み込んだうえで…

```js
// 1
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
```

ページ遷移時に以下を呼び出しています。
```js
// 2
window.gtag('config', トラッキングID, {
      page_path: asPath,
});
```

機能導入直後ということでデバッグしやすいように「2」が発火されるタイミングでconsoleへ「Track PV:◯◯」と出力するようにしています。このようなメッセージがブラウザのconsoleに表示されているかどうかご確認いただけますか？

よろしくお願いします。

**Comment by catnose99** [comment]
PV数がほぼゼロなのは、現状だとほとんどがQiitaからの転載記事というのもあるかもしれません。
Googleは同一コンテンツを検索結果に載せないようにするので、転載コンテンツの検索流入はほぼゼロになるはずです。

**Comment by obata15** [comment]
> 機能導入直後ということでデバッグしやすいように「2」が発火されるタイミングでconsoleへ「Track PV:◯◯」と出力するようにしています。このようなメッセージがブラウザのconsoleに表示されているかどうかご確認いただけますか？

こちら確認しましたところconsole上では正しくログが表示されていました。
昨日の時点でも、Windows 10のEdgeでネットワークタブからトラッキングIDを検索しまして、リロード時には www.googletagmanager.com/gtag/js と www.google-analytics.com/g/collect 、ページ遷移には collect のみにリクエストが飛んでいることを確認できていたので、Google Analytics側の設定ミスを可能性もありそうだと考えていました。

> もしかすると…ですが、ページのデータがキャッシュされている可能性があります。

昨日と同様の環境で再調査しましたところ、現在は100%ではないものの、ページ遷移時にもPVが記録されることが多くなっているようです。
もしかすると、ページキャッシュかGoogle Analytics側でコードを発行した直後なので動作が不安定だったなどの影響があったのかもしれません。
お騒がせして申し訳ないです🙇

> PV数がほぼゼロなのは、現状だとほとんどがQiitaからの転載記事というのもあるかもしれません。
> Googleは同一コンテンツを検索結果に載せないようにするので

外部流入は少ないと思うのですが、いいねがつくペースやサイト内流入などを考えるとさすがに少なすぎではと思って検証したところ再現したという流れなので、もしかするとPVがない事自体は正かもしれないです😭

ちなみにオリジナル記事との重複コンテンツの状態も定期的に調べているのですが、タイトルを書き換えたりした場合に、（サイト内ページ数の差なのか）Qiitaの方のインデックスがずっと更新されずZennの方だけ更新されるということがあり、そういった場合にはZennの記事の方が検索に出てくるようです。
例えばシークレットウィンドウで「Google Admin Toolbox」でGoogle検索すると私のZennの記事が6番目に出てくるので、意外とQiitaからの転載記事でもSEO的に戦えるのでは？と思っています。

**Comment by catnose99** [comment]
すごく丁寧にありがとうございます！

> 例えばシークレットウィンドウで「Google Admin Toolbox」でGoogle検索すると私のZennの記事が6番目に出てくるので、意外とQiitaからの転載記事でもSEO的に戦えるのでは？と思っています。

お・・・・・本当ですね
Qiitaに勝ってるw

不勉強でした。ありがとうございます。一度クローズしますが、何かありましたらまたお気軽にOpenしてください。
