### ISSUE TITLE
スクラップに貼ったgifが表示されないことがある

### ISSUE THREAD

**Issue by skanehira** [zenn-dev/zenn-roadmap#170]
# 事象
gifが表示されないことがあるみたいです
↓にgifを貼りましたが、表示されていない状態です。

https://zenn.dev/skanehira/scraps/a359ad73892314d65e6f#comment-f7086e9f725db079c63b

## 環境
OS: Ubuntu20.04 LTS
ブラウザ: Vivaldi

**Comment by catnose99** [comment]
Gif周りで何度もすみません。
対応します。

**Comment by catnose99** [comment]
@skanehira 
修正しました！もし、直っていない部分があれば、編集などをした後に再保存してみていただければと思います。
