### ISSUE TITLE
スクラップでCtrl+Enterで改行されてしまう

### ISSUE THREAD

**Issue by skanehira** [zenn-dev/zenn-roadmap#174]
## 事象
スクラップのエディタでCTRL(Cmd)+Enterで更新できるが、その際に改行もされてしまう

## 希望
ショートカットで更新する際は改行させないようにしたい

**Comment by catnose99** [comment]
あれれ…再現せずですね…。

![Nov-26-2020 23-55-31](https://user-images.githubusercontent.com/34590683/100365472-e3a2bc80-3042-11eb-94ca-3659d7e902f9.gif)

環境はUbuntu + FireFox or Chromeとかですかね

**Comment by catnose99** [comment]
リストで再現できました！確認します

**Comment by skanehira** [comment]
あ、すいません
リストを使うとおきます…

**Comment by catnose99** [comment]
@skanehira 対応しました！ご報告ありがとうございました！
