### ISSUE TITLE
Scrapのテキストフィールドでアイテマイズの改行時に文字を打ち始めるまで行が拡張されない

### ISSUE THREAD

**Issue by Kyome22** [zenn-dev/zenn-roadmap#175]
## 事象

Markdownのアイテマイズを入力していて改行すると次のアイテマイズの記号が挿入されるのは良いが、行末まできている時に改行してもテキストフィールドが拡張されない。

![demo](https://user-images.githubusercontent.com/19896354/100367609-d0452080-3045-11eb-8008-fc2cf2debe07.gif)

## 希望

改行した時点で行が増えて（テキストフィールドが拡張されて）欲しい。

**Comment by catnose99** [comment]
@Kyome22 
対応しました！ご迷惑をおかけしてすみません

**Comment by Kyome22** [comment]
@catnose99 おぉ、改善されているのを確認しました！ありがとうございます。
