### ISSUE TITLE
バグ: 通知が99を超えた時に全て99に丸まる。99+もしくは3桁数字を許容しても良いと思う

### ISSUE THREAD

**Issue by ulwlu** [zenn-dev/zenn-roadmap#182]
いつも素敵なサービスの運営ありがとうございます。

事象

![3C2BD903-F0DF-45E0-B148-17BC5687BC75](https://user-images.githubusercontent.com/41639488/101105851-fce2d480-3611-11eb-87b6-58851dfad324.png)

↓ 99からいくら通知が増えても(画像で言うとlikeが133→135に増えてる)

![3F083CC3-0D40-456B-B3A4-2CFCE06EFE5A](https://user-images.githubusercontent.com/41639488/101105845-fa807a80-3611-11eb-96e4-61149f7d1f4f.png)

**Comment by catnose99** [comment]
ありがとうございます。確認してみます！

**Comment by catnose99** [comment]
<img width="177" alt="スクリーンショット 2020-12-04 10 53 14" src="https://user-images.githubusercontent.com/34590683/101111638-ef801700-361e-11eb-97cd-91b7a75acfae.png">

+が下にはみ出てしまっていました…
（よく見ると白いのが笑）

近日中に直します！

**Comment by ulwlu** [comment]
！！
本当ですね、いたんですね+君、、、
ありがとうございます！よろしくお願い致します

**Comment by catnose99** [comment]
対応しました

**Comment by ulwlu** [comment]
(๑´ω`ﾉﾉﾞぱちぱちぱち✧
ありがとうございますmm
