### ISSUE TITLE
本の購入をコンバージョンとして測定したい

### ISSUE THREAD

**Issue by dijzpeb** [zenn-dev/zenn-roadmap#186]
本が購入された時、Google Analyticsでイベントとして測定できるとありがたいです。

決済まで完了したかどうかの測定がセキュリティ上難しいようでしたら、購入ボタンが押されたかどうかだけでも測定できるようになると助かります。

お忙しい中恐縮ですが、よろしくお願いいたします。

**Comment by catnose99** [comment]
よく検討してみたのですが、このようなプラットフォームでAnalyticsで個別にイベントを計測するのはやはり難しいです…。理由はいくつかありますが、特にセキュリティの問題が大きいです。
すみません。
