### ISSUE TITLE
コメントのマークダウン内で数式を使えるように

### ISSUE THREAD

**Issue by skypenguins** [zenn-dev/zenn-roadmap#187]
記事内では正常に反映されるのですが、Discussion内ではプレーンテキストのままになります。

**Comment by catnose99** [comment]
そちらについては現状では仕様ですね…。
（記事に負荷がかからないように埋め込み系や画像を制限しています）

ただ、数式については議論するうえで使えないと不便だと思うので対応しようと思います。
今しばらくお待ちください。

**Comment by catnose99** [comment]
対応しました。
