### ISSUE TITLE
スクラップの新規スレッド作成時にプレビューが残ってしまう

### ISSUE THREAD

**Issue by softoika** [zenn-dev/zenn-roadmap#188]
プレビューを表示した状態で投稿するとプレビューが残ります。
プレビューの表示を切り替えるとリセットされるので、そこまで大きなバグではないとは思います。(ややびっくりする)
![zenn_scrap](https://user-images.githubusercontent.com/25437304/101335643-d1374700-38bc-11eb-92ad-a90e1b266e38.gif)

**Comment by catnose99** [comment]
これはたしかにそうですね。修正します。

**Comment by catnose99** [comment]
対応しました

**Comment by softoika** [comment]
素早い対応ありがとうございます！
