### ISSUE TITLE
引用文に見出しを入れるとスタイルが意図した形にならない

### ISSUE THREAD

**Issue by yamanoku** [zenn-dev/zenn-roadmap#191]
該当URL：https://zenn.dev/yamanoku/articles/c69decedfb1699

```markdown
> ### 最大幅について
> メインコンテンツの最大幅は80chに設定しています。chはチェーンと呼ばれ、文字のサイズによって可変する単位です。
> 
> この設定にすることのメリットとして、長文が読めない読字障害の利用者のサポートができたり、文字サイズが大きくなるに従ってテキストの一部が欠けて読めなくなるような事態も発生しにくくなります。
> https://yamanoku.net/about/#about:max-width
```

<img width="532" alt="Screen Shot 2020-12-10 at 8 05 13" src="https://user-images.githubusercontent.com/1996642/101699651-de238880-3abe-11eb-8532-edb9581483f0.png">

`<blockquote>`内で見出しの`::before`が有効になっているため、その領域も含めたスタイルになっている

---

Scrapsの状態は問題なさそう。これと同様になれれば良さそう

<img width="766" alt="Screen Shot 2020-12-10 at 8 33 00" src="https://user-images.githubusercontent.com/1996642/101701493-60617c00-3ac2-11eb-8e3c-de8aa2a02ad5.png">

**Comment by catnose99** [comment]
ご報告ありがとうございます。記事の方だと固定ヘッダー用のスクロール調整のために見出しにネガティブマージを使用しているのが原因ですね。調整しようと思います。

**Comment by catnose99** [comment]
対応しました。

**Comment by yamanoku** [comment]
ありがとうございます！
