### ISSUE TITLE
自動デプロイをスキップできるようにする

### ISSUE THREAD

**Issue by ress997** [zenn-dev/zenn-roadmap#193]
パッケージの更新などでリポジトリを更新することがあるので、CIみたいに `[ci skip]` みたいな特定のワードを検知してデプロイしないほうが負荷がかからないかもしれない

例: https://github.com/ress997/zenn-content/commit/4f062244685d48c130cd0676b8875011155116da

**Comment by catnose99** [comment]
CIみたいにコミットやプルリクの文字列からスキップを検知するの良いですね。実装的も簡単そうなのでやろうと思います。

**Comment by catnose99** [comment]
対応しました
