### ISSUE TITLE
zenn.dev上の画像をリセットしたい

### ISSUE THREAD

**Issue by wataru72v** [zenn-dev/zenn-roadmap#194]
github上に配置した画像を本の中で読み込ませています。
github上の画像を名前はそのままで別のものへ差し替えたところ、
localhostには反映されましたが、zenn.dev上で表示を確認すると反映されないようでした。
（ブラウザのキャッシュクリア、別端末での確認などは試しましたが、上記と同じでした）

内部的に一度画像を落としてると思うのですが、
内部で保持している画像をリセットする機能を実装していただけませんでしょうか。

**Comment by catnose99** [comment]
画像にプロキシをかけているので、画像がキャッシュされてしまっていると思います。
プロキシのキャッシュ期間を制御するのは難しいので、お手数ですが、クエリパラーメーターをつけていただく必要があると思います。


```
![alt](https://foo.bar/example.png?date=20201212)
```
みたいな感じですね…

お手数ですがよろしくお願いします。

**Comment by wataru72v** [comment]
回答ありがとうございます。
上記で対応させていただきます。
