### ISSUE TITLE
Scrapsで行頭以外に置いたリンクがリンクカード化されるようになった

### ISSUE THREAD

**Issue by okuoku** [zenn-dev/zenn-roadmap#195]
Scrapsで行頭以外に置いたリンクがカード化されるように挙動が変化したようです。

```md
prev: https://zenn.dev/okuoku/scraps/b485da18176fdc
next: https://zenn.dev/okuoku/scraps/c236209827218e
```

![image](https://user-images.githubusercontent.com/100813/102648754-6edb2200-41ab-11eb-878b-eda9d18f1558.png)

従来は、行頭に何か文字を入れることでリンクのカード化を回避することが常に可能で、GFMの改行ルールに従っていました。

https://zenn.dev/okuoku/scraps/b485da18176fdc

![image](https://user-images.githubusercontent.com/100813/102649623-d776ce80-41ac-11eb-9c26-839994957bbe.png)

[ZennのMarkdown記法](https://zenn.dev/zenn/articles/markdown-guide#%E3%82%B3%E3%83%B3%E3%83%86%E3%83%B3%E3%83%84%E3%81%AE%E5%9F%8B%E3%82%81%E8%BE%BC%E3%81%BF) では、URLのみの行が展開対象であると記述されています。

> URLだけが貼り付けられた行があると、その部分がカードとして表示されます。

**Comment by catnose99** [comment]
これは意図していない挙動です。対応します！

**Comment by catnose99** [comment]
@okuoku こちら修正しました。ご迷惑をおかけしてすみませんでした。
