### ISSUE TITLE
エディタ内のリスト先頭で改行すると現在行が破棄される

### ISSUE THREAD

**Issue by okuoku** [zenn-dev/zenn-roadmap#196]
エディタ内でリストに項目を挿入しようとして行頭で改行すると、その行が削除されるようです。

```
- aaa
- bbb
- (ここで改行)ccc
```

↓

```
- aaa
- bbb

```

これは他のサイトの挙動と異なっています。

### Qiita

Qiitaはリストを終了し、現在行を段落とします。

```
- aaa
- bbb

ccc
```

### GitHub 、 Hackmd.io

GitHubやHackmd.ioは、空の要素を挿入します。

```
- aaa
- bbb
- 
- ccc
```

**Comment by catnose99** [comment]
あ、本当ですね…。修正します！

**Comment by catnose99** [comment]
@okuoku こちら修正しました。ご指摘ありがとうございました。
