### ISSUE TITLE
スクラップのエディタ上では，数字が先頭にある行で改行するときの挙動がおかしい

### ISSUE THREAD

**Issue by eduidl** [zenn-dev/zenn-roadmap#197]
## 環境

OS: Ubuntu 20.04
ブラウザ：Vivaldi 3.5.2115.73 (Stable channel) (64-bit)

## 内容

スクラップ上で数字が先頭の行で改行するときの挙動がおかしいようです．
基本的には改行すると行が丸ごと消えます．

```
1aa（カーソル）
```

↓改行

```

（カーソル）
```

ただし，文字数が多い？と以下のように順番付きリストのような挙動になります．

```
1aaa（カーソル）
```

↓改行

```
1aaa
2.（カーソル）
```

上記の事象はarticleのエディタの方では起こりません．

**Comment by catnose99** [comment]
@eduidl ありがとうございます。こちらちょうどさきほど同じissueを報告していただきまして現在対応中です。申し訳ないのですが、今しばらくお待ちください。

Duplicate of #196

**Comment by eduidl** [comment]
@catnose99 関連しているとは思うのですが，そもそも`.`を書いていないのにリスト扱いされているのが何か変だなと思っています．

**Comment by catnose99** [comment]
@eduidl あ、そういうことですか！
すみません、確認します。

**Comment by catnose99** [comment]
@eduidl 修正しました。丁寧にご指摘いただきまして、ありがとうございました。
