### ISSUE TITLE
スクラップでコメントできないときに返信の項目・アイコンを表示しない

### ISSUE THREAD

**Issue by ress997** [zenn-dev/zenn-roadmap#201]
作成者以外のコメントが許可されていないときにスクラップ右上にある🔽ボタンから**返信**の項目や左下の💬ボタンを表示しないようにしてほしい

現在一番下に `作成者以外のコメントは許可されていません` としか表示されておらず、最初押しても反応がないのでバグかなと思ってしまいました。

**Comment by catnose99** [comment]
ありがとうございます。対応します！

**Comment by catnose99** [comment]
対応しました
