### ISSUE TITLE
イベントのFeedがほしい

### ISSUE THREAD

**Issue by yuki-ycino** [zenn-dev/zenn-roadmap#207]
https://github.com/zenn-dev/zenn-roadmap/issues/205 に関連する話なのですが、例えば投稿やLikeのイベントを取得できるFeedがあれば設計を汚さずにベターな実装にできるんじゃないかと思いました。
上記Issueを作成しておいてあれなんですが（更新頻度やフィードを取得する間隔によるとは思うのですが）、記事のフィードとイベントのFeedを連携させることで、記事の情報管理をするのが設計的にはいいかもしれません。

**Comment by catnose99** [comment]
ご提案ありがとうございます！
RSSフィードだと表示可能な数に限りが出てきたりするので（RSSフィードだとページネーションが難しい）、APIでやりたいと思っています。
すみませんが、しばらくお待ちください。

**Comment by yuki-ycino** [comment]
ありがとうございます。
APIの提供を期待しています。

**Comment by catnose99** [comment]
duplicate of #205
