### ISSUE TITLE
RSSフィードに著者情報の追加

### ISSUE THREAD

**Issue by azu** [zenn-dev/zenn-roadmap#211]
`https://zenn.dev/feed` などのRSSフィード に `<dc:creator>` 要素がないため、RSSリーダーから見るとだれが書いたかわからない状態になっています。
タグやトレンドなどのRSSフィードには複数の著者が混在するので、`<dc:creator>` または `<author>` 要素を追加していただけると助かります。

[Inoreader](https://inoreader.com)での表示例。

![image](https://user-images.githubusercontent.com/19714/103512474-1e9ed800-4eac-11eb-857c-c1575a928452.png)

RSSの `<author>` はメールアドレスなので、

- https://www.rssboard.org/rss-2-0#element-channel-item-author

`<dc:creator>` で作者の名前を入れるのが良さそうな気がしています。

- [dc:creator](https://wiki.suikawiki.org/n/dc:creator)
- https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/creator

```diff
<?xml version="1.0" encoding="utf-8"?>
- <rss version="2.0">
+ <rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/">
    <channel>
        <title>Zennのトレンド</title>
        <link>https://zenn.dev</link>
        <description>Zennの現在のトレンド投稿を表示します</description>
        <lastBuildDate>Mon, 04 Jan 2021 05:45:31 GMT</lastBuildDate>
        <docs>https://validator.w3.org/feed/docs/rss2.html</docs>
        <generator>zenn.dev</generator>
        <language>ja</language>
        <image>
            <title>Zennのトレンド</title>
            <url>https://zenn.dev/images/logo-only-dark.png</url>
            <link>https://zenn.dev</link>
        </image>
        <copyright>(C) Zenn</copyright>
        <item>
            <title><![CDATA[保守性の高いソフトウェア開発のTips集]]></title>
            <link>https://zenn.dev/riku/books/36d9873ee1c0e6</link>
            <guid>https://zenn.dev/riku/books/36d9873ee1c0e6</guid>
+           <dc:creator><![CDATA[谷出陸]]></dc:creator>
            <pubDate>Fri, 01 Jan 2021 15:52:39 GMT</pubDate>
            <description><![CDATA[保守性の高いソフトウェアの開発に役立つ様々なTipsを書いた。
特定の言語にとらわれずあらゆる場面で役立つことを集めた。

著者はAtCoder水色の達人です。]]></description>
            <enclosure url="https://zenn.dev/images/logo-only-dark.png" length="0" type="image/png"/>
        </item>
```

この変更の利点

- 多くのRSSリーダはauthor情報を表示できるので一覧性がよくなる
- RSSリーダの機能でのフィルタリングなどの分類に利用できる

参考: `<dc:creator>` 要素があるフィードの例

- `https://github.blog/feed/`

![image](https://user-images.githubusercontent.com/19714/103518282-d6d17e00-4eb6-11eb-81df-8c1b311366a7.png)

**Comment by catnose99** [comment]
@azu 
見落としておりました。変更例や利点の説明まで詳しくありがとうございます。
近日中に対応します。

**Comment by catnose99** [comment]
メモ
パッケージ[feed](https://www.npmjs.com/package/feed)が現状では`<dc:create>`に対応していないので、カスタムタグを指定できる[rss](https://www.npmjs.com/package/rss)へ乗り換え

**Comment by catnose99** [comment]
対応しました。

**Comment by azu** [comment]
ありがとうございます。
確認できました。
![image](https://user-images.githubusercontent.com/19714/103599376-55c2c700-4f48-11eb-8895-79084d34e9e1.png)
![image](https://user-images.githubusercontent.com/19714/103599380-59eee480-4f48-11eb-9bd1-ca701adae1a7.png)

**Comment by catnose99** [comment]
丁寧にありがとうございました。
