### ISSUE TITLE
Sign inの表記・動作について

### ISSUE THREAD

**Issue by ress997** [zenn-dev/zenn-roadmap#212]
現在ログインするためには下記の7箇所存在します。(軽く確認しただけですが)
- 全体
  - Header `Sign in`ボタン
  - Footer `今すぐはじめる`ボタン
- ユーザーページ、記事ページ
  - `Follow`ボタン
- 記事ページ
  - `サポートする`ボタン
  - コメントの`ログインする`ボタン
- 有料本ページ
  - `XX円で購入`ボタン
  - コメントの`ログインする`ボタン

全体で共通しているボタンは`/enter`へのリンクへとなっており、ほかはポップアップでログインができ**見ていたページへ戻る**ようにになってます。

他にも `/enter` では
> 新規登録、ログインのどちらも以下のリンクから行うことができます。

と表記されているので初回使用者はわかりやすいと思いますが記事ページでは`Sign in`や`ログインする`など表記の揺れ動作の違いがあります。

そこで見ていたページへ戻る動作だけでも統一してほしいと思いissueをたてさせていただきました

**Comment by catnose99** [comment]
こちら対応しました。ご指摘ありがとうございました。

**Comment by ress997** [comment]
ログイン後強制的にトップに戻る仕様だったので他端末で読んでから ❤️  つけようと思ったときに困ってました…
対応ありがとうございます！
