### ISSUE TITLE
ロゴを使わせてもらいたい

### ISSUE THREAD

**Issue by SuguruOoki** [zenn-dev/zenn-roadmap#215]
# 概要

TechTrainというサービスを運用しており、IDからZennのプロフィールに遷移するようにしたいと考えています。
その際に、クリックする箇所にZennのロゴを使わせていただきたいです。

ロゴのガイドラインなど様々事情があるかと思います。
もし不都合などがありましたら、教えていただけますと助かります。
よろしくお願いします。

# ロゴを載せさせていただきたいサービスについて

[サービスLPURL](https://techbowl.co.jp/techtrain/)

## 載せさせていただきたいURL

https://techbowl.co.jp/techtrain/mentors/66
↑メンターごとに異なるIDとなるが、それぞれ同じような位置にZennがくる

* 上記URLのQiitaの隣にロゴをリンクとしてのせたい
* イメージとしてはQiita文字をクリックする箇所がZennはロゴとなる

<img width="316" alt="スクリーンショット 2021-01-16 0 57 58" src="https://user-images.githubusercontent.com/16362021/104749254-ed6cb480-5795-11eb-99d9-bc0310bbf59d.png">

**Comment by catnose99** [comment]
@SuguruOoki 
丁寧にありがとうございます。

どうぞご自由にご利用ください。
ロゴデータは下記のリンク先からダウンロード可能です。
https://zenn.dev/mediakit

**Comment by SuguruOoki** [comment]
ありがとうございます！使わせていただきます！！！
