### ISSUE TITLE
articles/explore内のリンクミス

### ISSUE THREAD

**Issue by umi-tyaahan** [zenn-dev/zenn-roadmap#217]
https://zenn.dev/articles/explore
下部の、「記事の一覧をチェック」のリンク先が
https://zenn.dev/books
になっています。
https://zenn.dev/articles
が正しいと思います。

**Comment by catnose99** [comment]
@umi-tyaahan ありがとうございます。すぐに対応します！

**Comment by catnose99** [comment]
対応しました。ご指摘ありがとうございました。
