### ISSUE TITLE
記事の編集画面で LaTex インライン記法 ($...$) の内部のマークアップが適用されてしまう

### ISSUE THREAD

**Issue by indigo13love** [zenn-dev/zenn-roadmap#219]
編集画面 (/edit で鉛筆を選んでいる状態) でインライン LaTex 記法 ($...$) を書くと、$ と $ の間にあるマークアップがテキストボックス上で適用されてしまいます。

Markdown のプレビューの確認画面(/edit で再生ボタンを選んでいる状態)や、実際に公開した画面では問題ないため、実影響はありません。あくまで編集画面が少し見にくくなってしまうだけです。

例えば、

```
Lorem $_a$ ipsum.
```

のような形で編集画面のテキストボックスに入力すると、`a$ ipsum.` の部分が `_..._` の途中であると判断されてイタリックになります。

同様の事象は、下記のようなインラインコードブロックでは発生しないので、

```
Lorem `_a` ipsum.
```

おそらく、インラインコードブロックと同じように処理することで回避できそうです。

**Comment by catnose99** [comment]
@indigo13love ご報告ありがとうございます。対応します！

**Comment by catnose99** [comment]
@indigo13love ご報告ありがとうございます。対応します！
