### ISSUE TITLE
スクラップ機能のエディタにおける「__」の解釈

### ISSUE THREAD

**Issue by SuguruOoki** [zenn-dev/zenn-roadmap#221]
# 概要

<img width="800" alt="スクリーンショット 2021-01-24 19 08 07" src="https://user-images.githubusercontent.com/16362021/105627068-bffbc700-5e77-11eb-8d36-8192212f6e99.png">

URLに「__」が含まれているとURLよりもそちらが優先されて解釈され、リンクにならない。

### 該当URL

`https://qiita.com/__init__/items/21b2604db54867f8c543`

https://zenn.dev/ohkisuguru/scraps/9004b199957700#comment-0885f6e2b2b61c

# コメント

いつもZenn使わせてもらってます！ありがとうございます！
直れば良いなーくらいの温度感です🙇‍♂️

**Comment by catnose99** [comment]
ご報告ありがとうございます。
おーほんとですね…。確認します！

**Comment by SuguruOoki** [comment]
URLエンコードすれば、ひとまずは回避できるかもしれません！
ご報告まで！

「_」: %5F

`https://qiita.com/__init__/items/21b2604db54867f8c543`
(https://qiita.com/__init__/items/21b2604db54867f8c543)
↓
`https://qiita.com/%5F%5Finit%5F%5F/items/21b2604db54867f8c543`
(https://qiita.com/%5F%5Finit%5F%5F/items/21b2604db54867f8c543)
でも表示できることを確認済みです。
表示前にエンコードするとかで問題ないかもしれません。

**Comment by catnose99** [comment]
丁寧にありがとうございます！
自動リンクは[markdown-it](https://github.com/markdown-it/linkify-it)により行われているため、その設定を見直すか、本家にプルリクを送ることになると思います。
今しばらくお待ちください。

**Comment by catnose99** [comment]
I guess we can close this issue when the PR below merged.
https://github.com/markdown-it/linkify-it/pull/96

**Comment by catnose99** [comment]
@SuguruOoki 
この件について詳しく調査したのですが、markdown-itを使用している限り根本的な解決は難しいようです。詳しい事情はこちらにまとめました。
https://zenn.dev/catnose99/scraps/e94c8e789f846a

# 対処法
Zennとしては、心苦しいのですが以下の方針を取ろうと思います。

1. 単純にリンク化されたURLを貼り付けたい場合は`<https://qiita.com/__init__/items/21b2604db54867f8c543>`のような形で`<`と`>`でURLを囲む
2. カード化したい場合は`@[card](https://qiita.com/__init__/items/21b2604db54867f8c543)`という記法を使う

2はこの件に対応するためについさきほど用意したのでzenn-cliを使っている場合は`npm install zenn-cli@latest`で更新する必要があります。

よろしくお願いします。
