### ISSUE TITLE
取り消し線の適用されない場所まで取り消し線の描画がされる

### ISSUE THREAD

**Issue by ress997** [zenn-dev/zenn-roadmap#222]
```md
- ~~Foo
    - bar
```

みたいな文章があるときに編集画面では間違った表示になってます
(プレビュー画面ではあっているので気になる程度ですが…)

#### 編集画面
<img width="238" alt="image" src="https://user-images.githubusercontent.com/48500247/105667455-9e094f80-5f1e-11eb-97d9-8833a77ae222.png">

#### プレビュー画面
<img width="160" alt="image" src="https://user-images.githubusercontent.com/48500247/105667470-a3ff3080-5f1e-11eb-9697-26c4cfc20ee4.png">

#### テストに使用したコード
```md
- ~~Foo~~
    - Bar
- ~~Foo
    - Bar
- ~~Foo
    - Bar~~
```

**Comment by catnose99** [comment]
ありがとうございます。
ライブラリ依存の部分なのですが、ややこしいので編集画面で取り消し線を表示しないようにスタイルを調整することにします。

**Comment by catnose99** [comment]
対応しました。
