### ISSUE TITLE
【 あったら嬉しい！ 】トップページからダッシュボードへ行く導線が欲しい

### ISSUE THREAD

**Issue by sushi-udon** [zenn-dev/zenn-roadmap#225]
## 現状の機能説明
<img src="https://user-images.githubusercontent.com/61356332/106037700-61a24300-611a-11eb-9c78-4f5e245db8ec.png" width="350">

現状、自分が把握しているフローですと
```
1. https://zenn.dev/ の右上の「Add new」を押す
2. 「（記事 or 本）を作成」を押す
3. 新規記事（本）のエディターが起動している状態のページで「＜」ボタンを押す
```
上記でダッシュボードページへたどり着くことができます。
そうではなく、トップページ (https://zenn.dev/)  から直接、ダッシュボードページへ飛ぶことができる導線が欲しいです。

### UXの向上
* Aへ飛ぶ導線ができることによって、上記1 ～ 3 のフローを1動作で済ませることが可能です。
* 動作の負担が減るだけでなく、操作性もよくなる見込みがあります。

**Comment by catnose99** [comment]
@sushi-udon 
右上の[Add new]に表示されているアイコンをクリックするとメニューが表示されて、そこからダッシュボードに飛ぶことができると思います。sushi-udonさんの場合、アイコン（アバター画像）の色が白なので見づらくなっていると思います。
（アップデートで線で囲むように変えます）

ご確認よろしくお願いします。

**Comment by sushi-udon** [comment]
@catnose99 
気づくことができず、申し訳ありませんでした…！
コメント頂き、ありがとうございます。

このissue はclose いたします。
