### ISSUE TITLE
記事の編集リクエスト機能

### ISSUE THREAD

**Issue by nyshk97** [zenn-dev/zenn-roadmap#226]
記事を読んでいて、タイポや、コードブロックにシンタックスハイライトが効いていないことが気になる時があります。

記事の編集リクエスト機能をつけると、zennに投稿されている記事全体のクオリティが少し上がると思います。

ref
https://help.qiita.com/ja/articles/qiita-edit-request

**Comment by catnose99** [comment]
Zennではサービス自体に編集リクエストをつけるのではなく、GitHubリポジトリ上でコンテンツを編集するような形にしたいと考えています。

ref: https://github.com/zenn-dev/zenn-roadmap/issues/176
