### ISSUE TITLE
バグ（？）GitHub連携していないのに連携済みといわれて連携できなくなりました。

### ISSUE THREAD

**Issue by KeenS** [zenn-dev/zenn-roadmap#236]
# 現象

UI上GitHubリポジトリの連携はされていません。

![image](https://user-images.githubusercontent.com/4434568/107533560-6844b600-6c02-11eb-88cb-4ae1a6792f1f.png)

しかし画面からGitHub連携をすると既に連携されていると言われ、エラーになります。

![image](https://user-images.githubusercontent.com/4434568/107533531-60851180-6c02-11eb-8835-661f4c31ba07.png)

# 期待する動作

GitHub連携をすると一連の処理のあと正しく連携できる

# 再現手順

1. 他人のzenn.devをfork
2. そのリポジトリをGitHub連携
    + slugのコンフリクトなどでエラーになる
3. そのリポジトリをリネーム
4. 新たに自分のzenn.devを作成
5. GitHub連携を一旦解除
6. 再度連携しようとする
    +  ここで上記のエラーが起きる

# 環境

端末: デスクトップマシン
OS: Ubuntu 20.10
ブラウザ: Firefox 85.0

# 補足など

最初の画面の案内に従ってGitHubでのzennとの連携を一旦解除して再度連携を試しても同じエラーになりました。

他人のzenn.devをforkしたのは編集リクエストを送るためです。その後、forkしたことを忘れてサービスでzenn.devリポジトリを作ったのかと思って誤って連携してしまいました。間違いに気付いたあと色々操作をした結果こうなってしまいました。

* zenn: [@blackenedgold](https://zenn.dev/blackenedgold)
* 該当リポジトリ: [KeenS/zenn.dev](https://github.com/KeenS/zenn.dev)
* フォークしたあとリネームしたリポジトリ: [KeenS/uhyo-zenn.dev](https://github.com/KeenS/uhyo-zenn.dev)

**Comment by catnose99** [comment]
@KeenS 
詳細なご報告ありがとうございます。こちらでも再現できました。
さきほど対応しましたのでお手数ですが改めて連携を行ってみていただけますでしょうか。

**Comment by KeenS** [comment]
連携を試したら正常に連携できました。対応ありがとうございます。
