### ISSUE TITLE
プロフィールの「自己紹介」欄のURLが途中で切れてしまう

### ISSUE THREAD

**Issue by ymd-h** [zenn-dev/zenn-roadmap#240]
プロフィールの自己紹介欄にURLを含めるとリンクに変換されますが途中で途切れてしまいます。
おそらく、アンダースコア (`_`) が許容されていないようです。

含めようとしたURL: https://ymd_h.gitlab.io/cpprb/

実際に表示されたリンク: [ymd](https://ymd)_h.gitlab.io/cpprb/   (最初の3文字のみがURLと解釈)
文字列に貼られていたリンク先: https://ymd

実際の表示確認用の参考記事: https://zenn.dev/ymd_h/articles/35d88f7d739651

試した限りでは、「自己紹介欄」はマークダウン記法が有効ではなさそうでしたので、ユーザーがURL範囲を明示することはできないと認識しています。

個人のウェブサイト（＝ブログ）とは別に開発しているライブラリのURLを「自己紹介」に記載しているので、ウェブサイトの欄に逃げることもできませんでした。

**Comment by catnose99** [comment]
丁寧なご報告ありがとうございます。対応しますので今しばらくお待ちください。

**Comment by catnose99** [comment]
@ymd-h 
こちら対応しました。ご報告ありがとうございました。

**Comment by ymd-h** [comment]
@catnose99 

対応ありがとうございます。
期待通りに表示されていることを確認できました。

今後ともよろしくおねがいします。
