### ISSUE TITLE
スクラップのタイトルを編集したときにHTMLのtitle要素に変更が反映されない

### ISSUE THREAD

**Issue by KeenS** [zenn-dev/zenn-roadmap#242]
記事でも起きるかもしれませんが、未確認です。

スクラップのタイトルを変更した際にHTMLのtitle要素に変更が反映されません。

![image](https://user-images.githubusercontent.com/4434568/107932171-99393800-6fc0-11eb-87d9-4c35a89dc250.png)
↑タイトルにhogehogeを足してみたが、title要素には反映されていない様子

これはリロードすると反映されることから書き換え忘れかなと思うのですがどうでしょう。

**Comment by catnose99** [comment]
ご指摘ありがとうございます！修正しました🙏
