### ISSUE TITLE
【Safari】スクラップのエディターで日本語変換の確定のEnterで改行してしまう

### ISSUE THREAD

**Issue by mitsuyoshi-yamazaki** [zenn-dev/zenn-roadmap#243]
# 概要
リスト入力中に日本語変換の確定のEnterで改行してしまいます

## 環境
macOS Big Sur 11.0
Safari 14.0.1

## 発現条件
リスト入力中に日本語の変換を確定する
例）`- ほんじつはせいてんなり` と入力し、変換確定のためEnterを押す

## 発現しない条件
リスト以外の日本語入力
例）`ほんじつはせいてんなり`

リストに英語を入力
例）`- hello, world`

**Comment by catnose99** [comment]
@mitsuyoshi-yamazaki 
検証のためいくつか質問させてください。

- こちら記事のエディターで発生する問題でしょうか？（もしくはスクラップのエディターで発生しますか？）
- Google日本語入力などのIMEを利用されていますか？

可能であればChromeで同じ操作をした場合に同様の問題が再現されるか確認していただけるとありがたいです。

よろしくお願いします。

**Comment by mitsuyoshi-yamazaki** [comment]
確認しましたが、スクラップのエディターのみで発生し、記事のエディターでは発生しませんでした。
また、Chrome 88.0.4324.150 では発生しませんでした

**Comment by catnose99** [comment]
ありがとうございます！確認させていただきます。

**Comment by catnose99** [comment]
@mitsuyoshi-yamazaki 
こちら対応しました。お手数ですが、ご確認いただければありがたいです。
丁寧なご報告いただき、ありがとうございました。
