### ISSUE TITLE
間違った feed にアクセスすると、500 Internal Server Errorが発生する

### ISSUE THREAD

**Issue by ymd-h** [zenn-dev/zenn-roadmap#246]
# 現象
以下のページにアクセスすると Internal Server Error 500 が発生します。
 (Vercel がアプリケーションエラーだと表示している画面のように感じました。）
https://zenn.dev/articles/feed

# 経緯

Zenn の各種RSS はURLに `/feed` をつけてアクセスするため、
新着記事一覧 (https://zenn.dev/articles) でもRSSを取得できると思って当該URLにアクセスしたところ発生

存在しない間違ったURLにアクセスすると 404 が返されるので、500は意図していないバグだと認識しています。
私のように中途半端に `/feed` つければ良いと覚えているユーザーが間違えてアクセスする可能性があると思われます。

# 表示されたエラーログ

```
Application Error
The error occurred in the hosted application
```

```
500: INTERNAL_SERVER_ERROR
Code: `FUNCTION_INVOCATION_FAILED`
ID: `hnd1::w5fcc-1613805604466-f3ff8014ceb2`
```

# 併せて確認したもの

* https://zenn.dev/books/feed -> 500
* https://zenn.dev/scraps/feed -> 500
* https://zenn.dev/search/feed -> 500
* https://zenn.dev/topics/feed -> 404  (不思議なことに、これはOKなんですね)
* https://zenn.dev/about/feed -> 500
* https://zenn.dev/faq/feed -> 500
* https://zenn.dev/tech-or-idea/feed  -> 500

他にもアクセスできそうなページはありましたが、広範囲でエラーが発生していたので、ここで打ち切りました。
サーバー側に大量のエラーログを発生させるなど、サービス運営に負荷をかけてしまっていたら申し訳ございません。

**Comment by catnose99** [comment]
ご報告ありがとうございます。
こちら色々とややこしくて恐縮なのですが以前から問題として認識しています。

Next.jsで`getStaticProps`というものを使ってページをキャッシュするときに、実際にエラーを発生させないと404ページまでキャッシュされてしまう問題がありました。これを回避するために本来は404にすべきページで意図的にエラーを発生させていました。

ただ、おそらく[最近のNext.jsのアップデートでこの問題に対応できるようになった](https://qiita.com/foooomio/items/cb2f6b4c91f0358c147d)（？）気がするので、どこかのタイミングで見直すことにします。

丁寧なご指摘ありがとうございました。

**Comment by ymd-h** [comment]
早速の回答ありがとうございます。

その分野の方には知られている既知の問題だったのですね。
知らなかったので、500 を見て思わずぎょっとしてしまいました。

アップデートの件も含めて状況理解いたしました。
どこかのタイミングで修正いただけそうとのことでありがとうございます。

引き続き、よろしくおねがいします。

**Comment by catnose99** [comment]
@ymd-h こちら対応しました。ご報告ありがとうございました。

**Comment by ymd-h** [comment]
@catnose99 

ご対応ありがとうございました。
こちらでも、確認できました。

いつも素敵なサービスをありがとうございます。
