### ISSUE TITLE
文章の直後に箇条書きをはじめて行頭で改行すると直前の文字が意図せずずれる

### ISSUE THREAD

**Issue by KeenS** [zenn-dev/zenn-roadmap#249]
文章での説明が難しいですが以下の入力をすると箇条書きとは関係のない文字が移動してしまいます

1. 文章を書いたあと改行する
2. 箇条書きをはじめる（ `- `）
3. 箇条書きの項目は空のまま行頭にカーソルを移動
4. 改行する
5. 箇条書きの書き出し（`- `） が消える（仕様）と同時に1行前の最後の文字がカーソルの後ろに移動する（バグ）

https://user-images.githubusercontent.com/4434568/109084679-91f5f500-774b-11eb-9ef8-ec34c8de566e.mp4

ページ: スクラップ、記事のコメントでのみ確認（記事とbookはGitHub連携をしてしまったので確認できず）
OS: Ubuntu 20.10
ブラウザ: Firefox 85.0.1 (64bit)

備考: （エンジンごとに微妙に異なりますが）マークダウンでは箇条書きの前後に空行が必要なので空行を入れようとしたらこの現象が起きました

**Comment by catnose99** [comment]
とても詳しくありがとうございます。確認させていただきます。

**Comment by catnose99** [comment]
@KeenS 
こちら対応しました。ご報告ありがとうございました。

**Comment by KeenS** [comment]
ありがとうございます！
