### ISSUE TITLE
[質問] 非公式iOS/Androidアプリの公開について

### ISSUE THREAD

**Issue by kndoshn** [zenn-dev/zenn-roadmap#250]
#209 に関連していますが、 `https://api.zenn.dev/articles` のようなAPIを使った Zenn 閲覧用のモバイルアプリを作り「非公式」と明記して AppStore/Google Play Store に公開することは可能でしょうか。

**Comment by catnose99** [comment]
申し訳ないのですが、しばらくはAPIの仕様が変わる可能性が高いので、API機能をリリースするまではお待ちいただければと思います。

**Comment by kndoshn** [comment]
承知しました！

**Comment by kndoshn** [comment]
あ、 `Zenn Roadmap` に入れていただいてたんですね。Closeしてしまいました。
Reopenしておきます 🙇

**Comment by catnose99** [comment]
あ、Issueは自動でroadmapに仕組みになっています。いったんクローズさせていただきます。
