### ISSUE TITLE
ツイート埋め込み機能でリプライ元を表示しない機能がほしい

### ISSUE THREAD

**Issue by KeenS** [zenn-dev/zenn-roadmap#251]
Twitterのツイート埋め込み機能はいくつかオプションがあり、そのうちにHide conversationというのがあります。リプライツイートに対して、リプライ元を表示するかしないかを切り替えられます。これで生成された埋め込みタグは `blockquote` に ` data-conversation="none"` がつくようです。現在の記法だとこれを指示できないのですが、サポートできないでしょうか。`<ツイートのURL>?conversation=none` のような指定あたりが無難じゃないかなと思います。

![image](https://user-images.githubusercontent.com/4434568/109722391-fbfd1700-7bef-11eb-966a-210a909ea587.png)

```html
<blockquote class="twitter-tweet"><p lang="ja" dir="ltr">エントリー書きました<br><br>自由なスマホPinePhoneを試す<a href="https://t.co/yAHGHfvx5X">https://t.co/yAHGHfvx5X</a></p>&mdash; κeen (@blackenedgold) <a href="https://twitter.com/blackenedgold/status/1366872546616905731?ref_src=twsrc%5Etfw">March 2, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
```

![image](https://user-images.githubusercontent.com/4434568/109722455-0cad8d00-7bf0-11eb-8fb4-f3b435478c43.png)

```html
<blockquote class="twitter-tweet" data-conversation="none"><p lang="ja" dir="ltr">エントリー書きました<br><br>自由なスマホPinePhoneを試す<a href="https://t.co/yAHGHfvx5X">https://t.co/yAHGHfvx5X</a></p>&mdash; κeen (@blackenedgold) <a href="https://twitter.com/blackenedgold/status/1366872546616905731?ref_src=twsrc%5Etfw">March 2, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
```

**Comment by catnose99** [comment]
これについてはちょうど最近自分も困っていたところなので着手します。
やや破壊的な変更になってしまいますがデフォルトで`conversation="none"`にして、URLにクエリをつけたら元のツイートも含めて表示するようにしようと思います。

**Comment by catnose99** [comment]
@KeenS 

こちら対応しました。
以下の理由からやはりデフォルトではリプライ元を表示、`?conversation=none`をクエリパラメータに指定するとリプライ元を非表示にする仕様にしました。

- デフォルトの仕様は本家と合わせたい
- リプライが含まれることありきでツイートを埋め込んでいた過去の投稿で破壊的な変更となってしまう

お手数ですが、リプライ元を非表示にしたいツイートは`ツイートURL?conversation=none`という形にしていただければと思います。

↓ 例

![スクリーンショット 2021-03-03 17 06 53](https://user-images.githubusercontent.com/34590683/109774472-b833fd00-7c43-11eb-8b60-fc13f45c072d.png)


よろしくお願いします。
