### ISSUE TITLE
リンク展開時に、titleの取得が不正確なケースがある

### ISSUE THREAD

**Issue by terrierscript** [zenn-dev/zenn-roadmap#252]
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString
こちらのMDNのページを展開した際、titleが意図しないものが表示される現象を確認しました

https://asia-northeast1-zenn-dev-production.cloudfunctions.net/iframeLinkCard?url=https%3A%2F%2Fdeveloper.mozilla.org%2Fja%2Fdocs%2FWeb%2FJavaScript%2FReference%2FGlobal_Objects%2FDate%2FtoLocaleString
<img width="630" alt="スクリーンショット 2021-03-06 12 33 06" src="https://user-images.githubusercontent.com/13282103/110193613-3a0c6c00-7e78-11eb-83b8-b8ad57d4def7.png">

MDNのソースを見たところ、`<title>`タグがSVG内などに含まれており、こちらも表示していることが原因と考えられます
<img width="1129" alt="スクリーンショット 2021-03-06 12 35 29" src="https://user-images.githubusercontent.com/13282103/110193637-750e9f80-7e78-11eb-963e-9969724cc626.png">

titleを一つだけ出すか複数出すかなどは仕様的に悩ましい部分ですが、SVGのtitleタグは除去しても良いのかなと感じました。

---
参考までにtwitterでは表示されないようでした
<img width="525" alt="スクリーンショット 2021-03-06 12 37 26" src="https://user-images.githubusercontent.com/13282103/110193701-d9c9fa00-7e78-11eb-963e-4de4ccdb55a4.png">

**Comment by catnose99** [comment]
@terrierscript 
分かりやすいご報告をありがとうございます。

まだ検証できてないので正確には分からないのですが、リンク先のデータを取得する際に使用しているライブラリの挙動に原因がありそうです。
https://github.com/jshemas/openGraphScraper

来週中に確認・対応を行います。しばらくお待ちいただけると幸いです。

**Comment by catnose99** [comment]
ライブラリにPRを出したのでしばらくお待ちください。
https://github.com/jshemas/openGraphScraper/issues/118

**Comment by catnose99** [comment]
すぐにマージしてもらえた🙏

@terrierscript 
さきほど修正したものをリリースしました。既存のURLについては1〜2日ほどキャッシュが残ってしまうかもしれませんが、しばらくお待ちください。

↓ クエリをてきとうにつけたものでは問題解消を確認済み
https://asia-northeast1-zenn-dev-production.cloudfunctions.net/iframeLinkCard?url=https%3A%2F%2Fdeveloper.mozilla.org%2Fja%2Fdocs%2FWeb%2FJavaScript%2FReference%2FGlobal_Objects%2FDate%2FtoLocaleString?cache=20210308
