### ISSUE TITLE
GithubPush時に、articles以下にmdファイルがなくとも、mdファイルを読み込めるようにしてほしい

### ISSUE THREAD

**Issue by ryuseikurata** [zenn-dev/zenn-roadmap#253]
# やりたいこと
GithubPush時に自分のサイトにdeployするようにしているが、その時にzennにも自動deployしたい。(そもそもarticlesでdeployできるように個人的にすればいい話でもありますが、、）

**Comment by catnose99** [comment]
「プロジェクトのルートディレクトリに`.md`ファイルが配置されているときにも記事としてデプロイを行えるように」という認識で合っていますでしょうか？

こちら申し訳ないのですが対応が難しいです。というのもZennにはarticles以外にもbooksなどコンテンツの種類が色々とあり、デプロイ時の取り扱いが複雑になるためです。

恐れ入りますがご理解いただけますと幸いです。
