### ISSUE TITLE
frontmatterに必要でないpropertyがあってもdeployできるようにしてほしい

### ISSUE THREAD

**Issue by ryuseikurata** [zenn-dev/zenn-roadmap#254]
```
---
title: "幸福度を最大化するためのエンジニアの働き方をまとめてみた"
date: 2020-10-11T13:26:54+09:00
categories:
    - work
emoji: "🙌"
type: "idea" # tech: 技術記事 / idea: アイデア
topics: ["work"]
published: true
---
```

以下のようなfrontmatterの形式でdeployしようと思ったのですが、できませんでした。
zennでエラーが以下のようなエラーが表示されていました

```
（Tried to load unspecified class: Time）
```

おそらく、dateの仕様が異なるものなのかな？と思いました。

**Comment by catnose99** [comment]
こちらエラーが出ないように変更しました。

このIssueとは関係ないですが、下記の記事で画像のエラーが出てしまっているのでご確認いただければと思います。
https://zenn.dev/shrek13/articles/practice-client-ddd
