### ISSUE TITLE
スクラップを編集するときにツイートの埋め込みがうまくいきません

### ISSUE THREAD

**Issue by risacan** [zenn-dev/zenn-roadmap#257]
スクラップを編集しようとしたときに、埋め込みボタンからツイートの挿入をしようとしたところ、単なる文字列と解釈されてしまいました。

![zenn挿入がうまく行かない](https://user-images.githubusercontent.com/13192318/110560823-f8d2cf80-8189-11eb-872a-436457aacf72.gif)

[ZennのMarkdown記法](https://zenn.dev/zenn/articles/markdown-guide#%E3%82%B3%E3%83%B3%E3%83%86%E3%83%B3%E3%83%84%E3%81%AE%E5%9F%8B%E3%82%81%E8%BE%BC%E3%81%BF)

こちらのリンクを確認し、エディタ上でURLのみで投稿しても結果は同じで、markdownの文字列として解釈されました。
クエリ文字列削除しても、結果は同じでした。

![スクリーンショット 2021-03-10 10 25 02](https://user-images.githubusercontent.com/13192318/110561365-ead17e80-818a-11eb-9b3a-7fa6a78ac831.png)

ツイートを埋め込めると嬉しいです！
zenndev応援してます。 📣

**Comment by catnose99** [comment]
ご報告ありがとうございます。
こちら本当に本当に申し訳ないのですが、使用しているmarkdownパーサ（markdown-it）の仕様により現状は解決できない部分になっています。
具体的には、URLの`/`の区切りの間にアンダースコア（`_`）が2つ含まれていると斜体とみなされて自動リンクにならないというものです。

↓ 詳細

https://zenn.dev/catnose99/scraps/e94c8e789f846a

上記リンク先に書かれているように、markdown-itではこの問題は仕様だとして解決しない方針のようなので、Zennではmarkdownパーサを変えない限りこの問題を解決できません。

そこでお手数をおかけして恐縮なのですが`@[tweet](ツイートのURL)`という記法を用いていただければと思います。埋め込みボタンからの挿入は`@[tweet](ツイートのURL)`の形式に変えておこうと思います。

関連するIssue
https://github.com/zenn-dev/zenn-roadmap/issues/221

**Comment by risacan** [comment]
了解です！
