### ISSUE TITLE
zenn new:article の使い方についての説明に、article フォルダを事前に作る必要があることを明記して欲しい

### ISSUE THREAD

**Issue by sadnessOjisan** [zenn-dev/zenn-roadmap#261]
https://zenn.dev/zenn/articles/zenn-cli-guide#%E8%A8%98%E4%BA%8B%E3%81%AE%E4%BD%9C%E6%88%90 に関して、` npx zenn new:article` は articles フォルダがないと失敗すると思うのですが、「事前にそのフォルダを作っておいてください」といった説明を追加しておくと良いかもと思いました。

**Comment by catnose99** [comment]
説明を追加しました。ご指摘ありがとうございます！
