### ISSUE TITLE
絵文字が使えるかどうかzenn-cliのpreviewで分からない

### ISSUE THREAD

**Issue by uhyo** [zenn-dev/zenn-roadmap#265]
Zennでは記事に絵文字を割り当てることができますが、Zennの仕様で使えない絵文字もあります。

使えない絵文字の場合でも、zenn-cliのpreview上ではそのことが分からず、実際にZennにデプロイしてみて初めて絵文字が使えないことが判明するという状況です（例えば🎞や🌬など）。

zenn-cli上でも、絵文字が使えないことを事前に警告してくれる仕組みがあればとても嬉しいです。

**Comment by catnose99** [comment]
@uhyo 
改めて色々と試した結果、一部の絵文字が使えない仕様自体を修正できました。
今は🎞や🌬などの絵文字も使用できるようになっています。

ご不便をおかけしてすみませんでした。
