### ISSUE TITLE
「埋め込み」機能にpaiza.ioが欲しい

### ISSUE THREAD

**Issue by xryuseix** [zenn-dev/zenn-roadmap#268]
[paiza.io](https://paiza.io/ja)とはオンラインエディタです.
現在対応いただいているオンラインエディタ(codepenなど)はJSなどWeb系でよく使われる言語しか対応していないものばかりです．

paiza.ioはiframeを用いて埋め込むことが可能です．
```html
<iframe src="https://paiza.io/projects/e/tJy3JewSnqbnT_LhXg1Z7A?theme=twilight" width="100%" height="500" scrolling="no" seamless="seamless"></iframe>
```
よろしくお願いいたします．

**Comment by cm-wada-yusuke** [comment]
要望ありがとうございます。現在対応しているものですが、特にWeb系だからというわけではなく、単純にユーザー数が多いものから選んで対応しております。`paiza.io` 拝見しました。いいサービスですね。こちら国内外問わず利用される段階になったら、対応を検討します。お手数ですが現時点においては GitHub gist などでコードを管理していただき、そちらを埋め込むようにご対応ください。

Zennの開発体制とメンテナンス体制に限りがあり、埋め込み対応については[dev.toなどが対応している埋め込み](https://dev.to/p/editor_guide)からさらに厳選しているとイメージいただければと思います。
