### ISSUE TITLE
Cookieをブロックしている場合もコンテンツの閲覧はできるように

### ISSUE THREAD

**Issue by catnose99** [zenn-dev/zenn-roadmap#3]
利用しているライブラリの関係で対応がわりと大変そう
おそらく https://vercel.com/ と同じようなエラーが発生している

**Comment by SaekiTominaga** [comment]
とくに有益な解決策を示すわけでもない、 Cookie 無効で閲覧しているユーザーとしての感想です。

現状、何より困るのが Cookie 無効でアクセスすると真っ白なページしか表示されず、どこにも Cookie に関するメッセージが出ないことです。すなわち、私を含む Cookie 無効ユーザーは「Cookie を有効にすれば解決する（かもしれない）」ということすら分かず、解決に向かう対応を取ることができない状況です。
私はたまたまこの Issue を見つけたので、8割方 Cookie 設定が原因だろうとは予想しているのですが、それでも今もって確証はありません（他にもブラウザの設定をカスタマイズしているので、他が原因である可能性は否定できません）。

また、ただ真っ白なページが表示されるだけなら昨今の Web では珍しいことではなく慣れたものですが（本来これは残念なことです）、ブラウザがページ応答の警告を出す状況はなかなか遭遇しないもので、最初に Zenn にアクセスしたときは何が起こったのかと焦りました。

以下は Chrome でアクセスしたときのダイアログです。「ページが応答しません　応答があるまで待つか、このページを離れるか、いずれかの対応方法をおとりください。」というメッセージが書かれていますが、いくら待っても状況は変わらないので、実質的に「ページを離れる」一択です。 Firefox など他ブラウザでも同様の事態になります。
![zenn_nocookie_dialog](https://user-images.githubusercontent.com/4138486/94362687-1e967b80-00f8-11eb-9bdf-5c674661fbb2.png)

また心情的に残念なのは、エンジニアの間で Zenn の記事や Zenn そのものについて盛り上がっているのに、私は何も見られないのでその波に乗れず、そもそも Zenn とは何なのかすらよく分からない状況で取り残されているのが悲しいです。

他のウェブサービスなら諦めて当該ドメインに対して Cookie を許可する設定変更をしているかもしれませんが、 Zenn はエンジニア向けのサービスであると認識しています。
そうであればサービス提供者が対応すべきことに対して、本来しなくてもいいブラウザの設定を変えることにはなおさら抵抗があるので、今のところ zenn.dev ドメインの Cookie を受け入れるようにはしていません。

他の Cookie 無効ユーザーが同意見であるとは限りませんが、少なくとも私はこういう理由で今も Zenn を見られない状況です、ということをお伝えする次第です。

**Comment by catnose99** [comment]
すみません。
現在いろいろと原因を探っているので、しばらくお待ちください。

**Comment by catnose99** [comment]
どうやらNext.js固有の問題のようで、Next.jsのShowcaseに載っているサイトの多くで同様の問題が発生します。
https://nextjs.org/showcase

すみませんが、対応に時間がかかりそうです。

**Comment by SaekiTominaga** [comment]
なるほど、「真っ白なページしか表示されない」のにはそういう事情があるのは分かりました。

しかし応答不能のダイアログが出るのも Next.js が原因ですか?
Zenn 以外のサイトでは見たことがありません（Next.js を使っているサイトであっても）。
ちなみにこのダイアログが出ている間（＝Zennのサイトをブラウザで開いている間）、コンピューターのCPU使用率が上がることも確認しています。

※なお、本コメントは現状を非難するものではなく、このやりとりを見た他の方が「Next.js を使うとこういうエラーダイアログが出てしまう」と思ってしまう風評被害を避けるために発言しています。

![「タスクマネージャー」のCPUグラフ（折れ線グラフ）。20%程度で推移している中、途中35～45%ほどまで上がっている。](https://user-images.githubusercontent.com/4138486/94368377-a5f6e580-011e-11eb-9fc4-671f06ad7c3d.png)

**Comment by catnose99** [comment]
手元でCookieをオフにして確認しても応答不能ダイアログの表示を再現できないので、原因究明ができていません。

**Comment by catnose99** [comment]
Next.js 10.0.1 でこの問題が解消されたようです。

↓ 該当するPR
https://github.com/vercel/next.js/pull/18261

近日中にcookieをオフにしても閲覧できるようになると思います。ご不便をおかけしてすみませんでした。

**Comment by SaekiTominaga** [comment]
ご連絡ありがとうございます。見られるようになる日を楽しみにしております。

**Comment by catnose99** [comment]
反映しました。見えないことがあればRepenしていただければと思います。
