### ISSUE TITLE
コードシンタックスでタブ文字の表示がスペース2文字に見える

### ISSUE THREAD

**Issue by skanehira** [zenn-dev/zenn-roadmap#32]
https://zenn.dev/skanehira/articles/2020-09-19-go-echo-bind-tips

↑の記事でコードシンタックスでタブ文字がスペース2文字に見えます。

![image](https://user-images.githubusercontent.com/7888591/93656490-da570b80-fa65-11ea-9795-f62683a615ad.png)

実際のコードは次になっています。
```go
type User struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

e.PUT("/users/:id", func(c echo.Context) error {
	id := c.Param("id")
	var u User
	if err := c.Bind(&u);err != nil {
		// error handling
	}
	u.ID = id
	db.Update(&u)
	...
})
```

**Comment by catnose99** [comment]
こちら先日タブスペースのサイズを小さくしてほしいという要望を受けたため、意図的に調整していました。
https://zenn.dev/zenn/articles/markdown-guide#comment-5879eedbd8cab143e376
https://github.com/zenn-dev/zenn-editor/commit/17269de3e68405836e38cc44108924a500c3f244

とはいえGitHubやdev.toなどのコードシンタックスを見ると、タブのサイズの調整を行っていないようですね…。
やはり調整すべきではないのかもしれません。

**Comment by catnose99** [comment]
ユーザーに馴染みのあるUIにしたいので`tab-size`の指定をやめてデフォルトの設定に戻すことにします。

**Comment by skanehira** [comment]
ありがとうございます
個人的に「書いたコードがそのままインデントが変わらず、色がついた形で表示される」のが一番しっくり来ますので助かります

**Comment by catnose99** [comment]
zenn.devへの反映を行いました
