### ISSUE TITLE
スクラップの管理画面で英字の大文字によるフィルタが正常に機能しない

### ISSUE THREAD

**Issue by nnabeyang** [zenn-dev/zenn-roadmap#341]
## 事象
スクラップ管理画面でフィルタに大文字を含む英字で検索すると`No scraps yet`になるが、小文字にしてから検索すると検索結果の出るケースを確認しました。おそらく、大文字を含む検索がヒットしないバグがあるのではと予想します。

## 発生したページのURL
https://zenn.dev/nnabeyang/scraps

## 発生した画面のスクリーンショット
<img width="1171" alt="スクリーンショット 2021-10-10 13 56 32" src="https://user-images.githubusercontent.com/441858/136682862-13341c27-e519-4a78-a5b2-3b5b7fb0e46a.png">

<img width="1207" alt="スクリーンショット 2021-10-10 13 58 20" src="https://user-images.githubusercontent.com/441858/136682886-a7b229d4-c986-4f61-b231-58367d95d8f3.png">

## 再現方法

1. https://zenn.dev/nnabeyang/scraps を開く
2. フィルタに`VoTT`と入力してフィルタをかける
3. 検索結果が`No scaps yet`になるのを確認する

## 環境
- Device: MacBook Pro (15-inch, 2019)
- OS: macOS 11.6
- Browser: Chrome 94.0.4606.71

**Comment by catnose99** [comment]
ご報告ありがとうございます。
こちらでも再現できました。
なるべく早く対応します。
