### ISSUE TITLE
「https://twitter.com/__mizu49__/status/1628380159631048704」が埋め込み形式にならない

### ISSUE THREAD

**Issue by ghost** [zenn-dev/zenn-roadmap#504]
## 事象

スクラップのコメントとして「 https://twitter.com/__mizu49__/status/1628380159631048704 」を書き込んでも埋め込み形式にならないようです。

## 発生したページのURL

https://zenn.dev/1s22s1/scraps/7b24d8b1d9731d

## 発生した画面のスクリーンショット

![Screenshot 2023-02-24 08 23 35](https://user-images.githubusercontent.com/77497543/221054058-ee8d36a7-7f34-4011-a35d-255088a874ad.png)

## 再現方法

スクラップのコメントとして「 https://twitter.com/__mizu49__/status/1628380159631048704 」を書き込む。

## 環境

- Device: PC
- OS: Google ChromeOS バージョン: 110.0.5481.112（Official Build） （64 ビット）)
- Browser: Google Chrome バージョン: 110.0.5481.112（Official Build） （64 ビット）

**Comment by uttk-dev** [comment]
@1s22s1 

報告ありがとうございます。

```markdown
@[tweet](https://twitter.com/__mizu49__/status/1628380159631048704)
``` 

と書くと表示されることを確認したので、そちらで対応して頂ければと思います。
