### ISSUE TITLE
Twitter の tweet 埋め込みが機能しない？

### ISSUE THREAD

**Issue by spiegel-im-spiegel** [zenn-dev/zenn-roadmap#51]
[Zenn の Markdown 記法](https://zenn.dev/zenn/articles/markdown-guide) で Twitter の tweet 埋め込みが機能していないように見えます。たとえば

```markdown
@[tweet](https://twitter.com/zenn_dev/status/1307804227071246336)
```

としても何も表示されません。書き方が間違っているのでしょうか...

**Comment by catnose99** [comment]
上記のテキストをコピペしてみたところ、私の環境では表示されたので書き方は合っていると思います。
レンダリング中は何も表示されないので、ネットワークの問題かもしれません。
ブラウザのコンソールに何か表示されていたりしますか？
また、ソースコード（HTML）上ではツイートはどのように表示されていますか？

**Comment by spiegel-im-spiegel** [comment]
ブラウザ側の問題でした。すみません。

私は Firefox で全てのトラッキング・コードをブロックしているのですが，これに引っかかったようです。
Zenn 側の問題ではないようですので，この Issue はクローズします。
