### ISSUE TITLE
[機能追加]トレンドや人気記事をRSSで配信してほしい

### ISSUE THREAD

**Issue by yutakatay** [zenn-dev/zenn-roadmap#52]
トレンドや人気記事、新着記事をRSSで配信してほしいです。Qiitaやdev.toはできるので機能追加をお願いしたいです。

**Comment by catnose99** [comment]
これは必要だと思うのでやりますね！

**Comment by yutakatay** [comment]
ありがとうございます。応援してます（とりあえず、記事を書いて）。

**Comment by catnose99** [comment]
# ToDo
- [ ] トレンド全体
- [ ] トレンドtech
- [ ] トレンドidea
- [ ] トピックごと
- [ ] ユーザーごと

**Comment by catnose99** [comment]
対応しました。
https://zenn.dev/zenn/articles/zenn-feed-rss

フィードの種類を増やすことは検討していますが、 #91 の後に対応したいと考えています。
一旦クローズします。
