### ISSUE TITLE
ズーミングや拡大縮小を有効にしてほしい

### ISSUE THREAD

**Issue by yamanoku** [zenn-dev/zenn-roadmap#53]
```
<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0, viewport-fit=cover">
```

Zennで一部拡大して読みたい場合（主にスマートフォン）に、現在はズーミングや拡大縮小ができません。
こちら自由に操作できるよう解除してくれるとありがたいです。

参考：[ズーミングや拡大縮小は無効にしてはなりません](https://dequeuniversity.com/rules/axe/3.5/meta-viewport)

**Comment by catnose99** [comment]
こちら自分でも意図していない値になっていました。
さきほど修正しました。
