### ISSUE TITLE
アイコンが使用されているリンクやボタンにroleと代替テキストを追加してほしい

### ISSUE THREAD

**Issue by ymrl** [zenn-dev/zenn-roadmap#54]
視覚障害をもつ技術者の同僚がおり、アクセシビリティが改善されるとオススメしやすくなるので、ご検討いただきたいです。

## ヘッダー右側、検索・通知・ユーザーメニューの各アイコン
![ヘッダーのスクリーンショット](https://user-images.githubusercontent.com/154188/93751946-e5ae6080-fc38-11ea-9505-5c014560cf50.png)

検索や通知のアイコンについては、a要素やbutton要素内にsvg要素が配置されているようです。
svg要素内にtitle要素やdesc要素でテキストを配置できるのですが、[ブラウザとスクリーンリーダーの環境によってはうまく読めないこともあり得る](https://www.slideshare.net/ssuser99dc16/html5fun-svg-accessibility)ようなので、a要素やbutton要素のaria-label属性に代替テキストを入れてしまうのが良いかと思います。
（このあたり正確な状況を把握できていません、すみません）

アバターアイコンはimg要素なので、alt属性として代替テキストを入れるのが良いかと思います。画像の内容を説明するには「ユーザーアバター」ですが、機能としてメニューの開閉があるので「ユーザーアカウントメニューを開く」のようなテキストになっているとよさそうです。

## 記事フッターと見出し横、Like・記事メニュー・シェアボタン

![記事フッターのスクリーンショット](https://user-images.githubusercontent.com/154188/93753106-9406d580-fc3a-11ea-9143-d83c92806933.png)
![見出し横のスクリーンショット](https://user-images.githubusercontent.com/154188/93753808-b0574200-fc3b-11ea-98fe-87e7b9aaf680.png)

記事メニューやシェアボタンについてはヘッダー部と同じです。

likeボタンについては、div要素として表示されていて、そもそもボタンであることに気付けない可能性があります。
これはbutton要素で実装するか、div要素に `role="button"` 属性を付与していただけるとありがたいです。
（role属性だけではキーボード操作ができない問題などもあるので、できればbutton要素を使っていただきたいです。この問題の詳細は拙著で恐縮ですが[WEB+DB PRESS vol.116](https://gihyo.jp/magazine/wdpress/archive/2020/vol116)の特集3の3章に詳しい説明がありますので、よろしければ参考にしてください）

**Comment by catnose99** [comment]
丁寧なご指摘、ありがとうございます。
対応します。

**Comment by catnose99** [comment]
検索や通知などのテキストによる説明のないアイコンに対して、`aria-label`で機能名を指定するようにしました。
一度closeしますが、ほかに対策できていない部分に気づかれた際はぜひ報告していただければ幸いです。
