### ISSUE TITLE
フォーカスインジケーターを表示してほしい

### ISSUE THREAD

**Issue by ymrl** [zenn-dev/zenn-roadmap#55]
#54 を書いているときに気付いたのですが、CSSで a, button, input, textareaなどに一律に `outline: none` が指定されおり、現在画面上のどこにフォーカスがあるのかわからなくなっています。
この状態だとキーボードでの操作が非常に難しいため、フォーカスインジケーターが表示されるように修正していただけるとありがたいです。

何かのReset CSSが由来だと思うのですぐに直すのが難しいかもしれませんが、aやbuttonについては `.outline` classを指定することでフォーカスインジケーターを表示できそうなので、主要なリンクやボタンだけでも改善されると嬉しいです。

なお、WCAGではフォーカスインジケーターの表示が求められています
https://www.w3.org/TR/2018/REC-WCAG21-20180605/#focus-visible
https://waic.jp/docs/WCAG21/#focus-visible
https://weba11y.jp/know-how/guidelines/visible-focus-indicator/

**Comment by catnose99** [comment]
outlineについてはやりかけの状態になってしまっていました。
こちら対応します。

**Comment by catnose99** [comment]
こちら対応しました。
