### ISSUE TITLE
コードブロック内の `-->` が矢印に変換されてしまう

### ISSUE THREAD

**Issue by spiegel-im-spiegel** [zenn-dev/zenn-roadmap#57]
地の文章の `-->` が矢印（→）に変換されるのはいいのですが，コードブロック内の

```
<!-- comment -->
```

のような記述でも矢印に変換されてしまいます。
コードブロック内では変換せずにそのまま表示させることは可能ですか？

**Comment by catnose99** [comment]
webのマークダウンエディターは作り直しているのでしばらくお待ちください

**Comment by catnose99** [comment]
こちらおそらく解決されたと思います。
