### ISSUE TITLE
MDエディタ内でShift+Tabを利用してインデントを上げると半角スペースがタブになってしまう

### ISSUE THREAD

**Issue by fagai** [zenn-dev/zenn-roadmap#60]
コードブロックに貼り付けたコードがインデントが下がっている場合があるため`Shift+Tab`を利用しています。(実際には出来ないはずですが、できるようになっていて助かります！）
そこで、半角スペースでインデントをしていた場合に`Shift+Tab`でインデントを上げると勝手にTabに変換がされてしまいます。

**Comment by catnose99** [comment]
現在のエディターにはEasyMDE（内部的にはcodemirrorを使用）を使っていて、その仕様だと思うのでちょっと対応が難しいです。
新しいエディターを開発中なので一旦クローズさせていただきます

**Comment by fagai** [comment]
了解です！待ってますー。
