### ISSUE TITLE
zenn cli ベースの書籍作成で、一部無料の設定ができるようにしてもらいたい

### ISSUE THREAD

**Issue by mikakane** [zenn-dev/zenn-roadmap#62]
現状 Web 上では設定できる（らしい）一部無料のコンテンツ設定を、
zenn cli ベースの GitHub 管理コンテンツでも設定できるようにしてもらいたい。

1.md などの chapter markdown 側の YFM で `free: true` などの形で設定できると嬉しい。

**Comment by catnose99** [comment]
こちらドキュメントに記載し忘れていました。
```
free: true
```
で無料公開にできます。

https://zenn.dev/zenn/articles/zenn-cli-guide#%E6%9C%AC%E3%81%AE%E5%90%84%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%AE%E5%BD%B9%E5%89%B2
