### ISSUE TITLE
リポジトリでチャプターを管理する際にファイル名を指定できるようにする

### ISSUE THREAD

**Issue by mikakane** [zenn-dev/zenn-roadmap#63]
現状は book の制作は 1.md 2.md 3.md などのファイル形式になっているが、

1.はじめに.md などの形で概要を挿入できるようにしてもらえると管理が楽で助かります。

**Comment by catnose99** [comment]
あーなるほどですね。半角スペースをどうするかなどの問題がありますが、一通り落ち着いたタイミングでちょっと考えてみます。

**Comment by terrierscript** [comment]
私もこちらあると嬉しいなと感じました。

個人的にはファイル名が日本語で無くても良いのですが、articlesのslugと同様1-intro.mdのように英数字が使えるか、数字だけでも1-2-3.mdまたは1.2.3.mdのように小段落の管理ができると使いやすくて有難いなと感じました

**Comment by catnose99** [comment]
あー、納得です。
既存の仕様を維持しつつ実装するのがちょっと難易度が高そうなので（.mdファイルとDBレコード上の整合周り=新規作成するか、更新するか等）一通り落ち着いたらよく検討することにします。

**Comment by catnose99** [comment]
# 現時点の問題
A) `1.md`〜`5.md`が存在するとして、3つ目のチャプターを差し込みたくなった場合に、チャプター4以降のファイルが1つずつずれてしまう
B) ビューアー上の各チャプターのURLが`/books/[book_slug]/[チャプター番号]`となっているため、チャプターへのリンクを維持することができない


# 対応方法
## A)
<details>
<summary>1.chapter_slug.md方式はよく考えると難しそう</summary>
間にチャプター差し込みたくなったときの管理がやはり大変そう

- 例）`3.◯◯.md`を差し込んだ場合、`4.◯◯.md`以降の数字をすべて1つずつずらす必要が出てくる
- 例）`3.example.md`と`3.other-example.md`が存在したときのデプロイ処理が難しい

</details>

### 現実的な対応
`slug.md`としてconfig.ymlで管理するのがベターっぽい？
例）`about.md`、`getting-started.md`、`question.md`があった場合、 config.ymlに以下のように記載する
```yaml
chapters:
  - about
  - getting-started
  - question
```
↑チャプター順に配列で並べてもらい、デプロイ時は["about.md", "getting-started.md", "question.md"]の順にチャプターを登録する。

#### 既存の形式からの移行
`1.md`〜`4.md`がある場合
```yaml
chapters:
  - 1.md
  - 2.md
  - 3.md
  - 4.md
```
のようにすればデプロイできるようにする

#### 注意点：slugは本ごとにユニークであればOKとする
- 例えば`about.md`というslugでチャプターファイルを作ったときにデプロイ時にユニークバリデーションに引っかかる可能性大。これは体験が良くない
- Webのアプリ上でチャプターを取得するときは、基本的にbookのslugと合わせてリクエストをかけるようにする


## B)
各チャプターのURLを`/books/[book_slug]/[chapter_slug]`とする

**Comment by catnose99** [comment]
対応しました。
https://zenn.dev/zenn/articles/deprecated-book-deployment
