### ISSUE TITLE
カバー画像が更新されない

### ISSUE THREAD

**Issue by Jxck** [zenn-dev/zenn-roadmap#67]
本の cover.png を更新して deploy しても、 zenn.dev 上で反映されない場合があるようです。
一旦コンテンツを削除してデプロイしなしたら解決しましたが、書籍が販売後だと難しいので改善されると嬉しいです。

また、 cover.png 画像を外部に置きたい (cacoo などで生成しそのリンクを使いたい) ケースがあるので、 cover.png をリポジトリに入れるのではなく、 URL で指定できるとより嬉しいです。

**Comment by catnose99** [comment]
お手数をおかけしてすみません。確認します。
URLからの画像の取得については、ものすごく重い画像を指すURLを指定された場合の対策（=トリミングorバリデーション）が必要だと思うので、時間がかかるかもしれませんが検討してみます。

**Comment by Jxck** [comment]
ありがとうございます。よろしくお願いいいたします。

**Comment by Jxck** [comment]
続報ですが、一度コンテンツを削除してからの cover の更新はいまのところうまくいっています。
以前もうまく行っていたので、何かを踏んだのかもしれません。

裏の仕組みがわからないので参考になるかわかりませんが、更新できなかった画像は
「背景を指定し忘れて作った透過 PNG 」だったので、それがリサイズ処理などで引っかかっていたのかも
という想像をしました。

何か再現したら追記します。

**Comment by catnose99** [comment]
裏の仕組みなのですが
1. GitHubからファイルのメタデータを取得してその中のhash値の比較
2. hashに変更がある場合のみ画像を再取得
というようにしているのですが、hash値の比較の部分でうまくいっていないような気がしています…。

ありがとうございます。
何かパターンがありましたらぜひ教えていただけますと助かります。

**Comment by catnose99** [comment]
さきほど内部に修正を加えておそらく問題の修正ができたのではないかと思います。
（原因がはっきりと分かっていないのでもしかすると再発するかもしれません）
同様の問題が発生した際は気軽にre-openしていただければと思います。

**Comment by Jxck** [comment]
ありがとうございます！
