### ISSUE TITLE
本のチャプターの表題をトップ画面で編集したい

### ISSUE THREAD

**Issue by kyokucho1989** [zenn-dev/zenn-roadmap#76]
さきに本のチャプターだけささっと構成したいので、
「+チャプターを追加」のページのところでチャプターの表題を編集できるようにして欲しいです。

現状だとチャプターのページに遷移しないと変更できないので。。。

**Comment by catnose99** [comment]
なるほど…検討します！

**Comment by catnose99** [comment]
本に編集はGitHubリポジトリ+CLIで使っている方がほとんどのようなので、CLIの改善を優先します
