### ISSUE TITLE
外部リンクを別タブで開けるようにしてほしい

### ISSUE THREAD

**Issue by HelloRusk** [zenn-dev/zenn-roadmap#80]
a タグに `target="_blank" rel="noopener noreferrer"` を入れてほしいです。
例えば、記事中に GitHub のソースコードのリンクが貼ってあった時、記事とソースコードを並行して見たいことが多いです。

**Comment by spiegel-im-spiegel** [comment]
個人的な意見として書いておきます。

不特定向けのサービスで target="_blank" は付けてほしくないです。これを付けてしまうと利用者側でウィンドウやタブのコントロールが難しくなり，気がついたら山ほどのタブができてるなんてことになりがちです。画面制御上どうしても別のウィンドウやタブにしたい場合はあると思いますが，それ以外はユーザの操作に任せてほしいです。

**Comment by catnose99** [comment]
僕は @spiegel-im-spiegel さんと同意見です。
Zennを閲覧するユーザーのほとんどはITエンジニアであり、ある程度のリテラシーを持っていると思います。
「Ctrl（⌘）」キーを押しながらタブを開くことで、別タブで開くことができることを知っている方も多いはずです。
すべてのリンクを別タブに開くようにするとストレスに感じる人もいると思うため、意図的に`target="_blank"`は入れていません。
