### ISSUE TITLE
ログインモーダルを閉じる挙動に関する改善要望

### ISSUE THREAD

**Issue by yamanoku** [zenn-dev/zenn-roadmap#85]
#55 の対応ありがとうございます👍 インジケーターがないと現在地がわかりづらかったので助かります。
上記Issueに付随して1件気づいたことがあったので記帳させてください。

<img width="700" alt="Screen Shot 2020-09-27 at 14 05 39" src="https://user-images.githubusercontent.com/1996642/94356584-30155e80-00cb-11eb-8eff-0df229c36225.png">

ログインしていない状態で記事の下部にあるコメント欄にフォーカスすると、
スクリーンショットのようなログインモーダルが出現します。
ただ、こちらを閉じるときにキーボード操作によって制御ができませんでした。

以下のような対応ができるとキーボード操作をすることができそうなので、考慮いただけると幸いです 🙏 

## モーダルの「閉じるボタン」にフォーカス、キーボード操作の制御ができるようにする

<img width="230" alt="Screen Shot 2020-09-27 at 14 05 56" src="https://user-images.githubusercontent.com/1996642/94356747-bda57e00-00cc-11eb-9d1f-43cdcbedc302.png">

モーダル内部のアイコンはSVGになっていますが、こちらがキーボードでフォーカスできない状態です。
（内部実装までは把握できておりませんが）以下のように`button`でラップした形で操作できると良さそうです。

```
<button type="button" aria-label="close" onClick="closeFunction()">
  <svg viewBox="0 0 27 27" width="15" height="15" class="login-modal-close"><path fill="currentColor" class="st0" d="M16.3 13.5l9.1-9.1c.3-.3.3-.9 0-1.2l-1.6-1.6c-.3-.3-.9-.3-1.2 0l-9.1 9.1-9.1-9.1c-.4-.4-.9-.4-1.2 0L1.6 3.2c-.4.3-.4.8 0 1.2l9.1 9.1-9.1 9.1c-.3.3-.3.9 0 1.2l1.6 1.6c.3.3.9.3 1.2 0l9.1-9.1 9.1 9.1c.3.3.9.3 1.2 0l1.6-1.6c.3-.3.3-.9 0-1.2l-9.1-9.1z"></path></svg>
</button>
```

## ESCキーでモーダルを閉じることができるようにする

モーダルのライブラリではESCキーによって閉じる制御ができるものがあります。
それと同様にこちらでもESCキー制御ができるとありがたいです。

**Comment by catnose99** [comment]
詳細にありがとうございます。落ち着き次第対応します！

**Comment by catnose99** [comment]
@yamanoku こちら対応しました！

- buttonタグおよびaria-labelの使用
- ESCキーでモーダルを閉じることができるように

ご指摘ありがとうございました。
