### ISSUE TITLE
img タグでの画像表示に対応してほしい

### ISSUE THREAD

**Issue by sogaoh** [zenn-dev/zenn-roadmap#86]
`<img width="298.08" alt="shortcut-setting.PNG (187.3 kB)" src="https://......PNG">` 
のような幅や高さ指定のある img タグに対応してほしい。

`![shortcut-setting.PNG (187.3 kB)](https://......PNG)`
でとりあえず画像を表示しているが、ドでかくて悩ましい。

refs https://zenn.dev/sogaoh/articles/2019_04_05_14_01-from-qrunch

<img width="852" alt="スクリーンショット 2020-09-27 15 57 52" src="https://user-images.githubusercontent.com/2090887/94358198-3fe86f00-00da-11eb-9874-7b7823688ecf.png">

**Comment by catnose99** [comment]
画像サイズの指定は現在でも可能です。
https://zenn.dev/zenn/articles/markdown-guide#%E7%94%BB%E5%83%8F

imgタグの直接挿入についてはXSS周りのセキュリティリスクが高いため、あまりやりたくないという感じです…。

**Comment by catnose99** [comment]
すみません、一旦クローズさせていただきます。

**Comment by sogaoh** [comment]
ありがとうございます。原稿を手直しして横幅調整ができました。
