### ISSUE TITLE
文字の色を変更できるようにしてほしい

### ISSUE THREAD

**Issue by TakuKobayashi** [zenn-dev/zenn-roadmap#87]
Qiitaからの記事の乗り換えをしようとしています。
Markdown記法では文字の色を変更することができる気泡が存在しません。
そのため、HTMLで文字の色の変更を記述していますが、`Zenn` では文字の色するHTMLを記述しても適用されません。
例えばQiitaでは以下のように記述したら赤文字で表記されるようになります。

```html
<font color="#FF0000">赤く表示されます</font>
```

こちら上記のような形でなくてもいいのでなんらかのHTMLの表記を用いて文字の色を変更できるような記述をすることは可能でしょうか?
もし記述できないようでしたら機能の追加をお願いできますでしょうか?
よろしくお願いします。

**Comment by catnose99** [comment]
ご要望ありがとうございます。
Zennでは読者が快適に読めるように、強調のパターンを増やしたくないと思っています。
読む側からすると、いろんな色で強調されているより、強調=太字とパターンが決まっている方が読みやすいと思います。
派手な色で装飾されるのを好まない方もいます。

意見をいただいたなか恐縮ではありますが、クローズさせていただきます。
