### ISSUE TITLE
画像コンテンツ の URL を 独自ドメインにしてほしい

### ISSUE THREAD

**Issue by anfangd** [zenn-dev/zenn-roadmap#90]
現在、一部の画像ファイルは以下のドメインから取得していると思います。

- storage.googleapis.com

このドメインが弾かれてしまい、画像が表示されないケースがあったので、可能であれば独自ドメインへの変更を検討して頂けると幸いです。

**Comment by catnose99** [comment]
なるほど。表示されなかった環境を教えていただけますか？

**Comment by catnose99** [comment]
ちなみに「ドメインが弾かれている」とのことですが、何かエラーメッセージがコンソールに表示されていたりしますか？

**Comment by anfangd** [comment]
@catnose99 

さっそくのご回答ありがとうございます。
環境情報は次の通りです。

- OS: Windwos 10 Pro
- Browser: 
  - Microsoft Edge 85.0.564.63, 64bit
  - Google Chrome 72.0.3632.121, 64bit
  - Firefox Quantum 65.0.1, 64bit

また、コンソール情報のエラーメッセージは次の通りです。

```log
Failed to load resource: the server responded with a xxxxxxxxxxxxxxxxx:1 status of 403 (Forbidden)

---
次のような、画像URL に対する Request が全て上記のようなエラーを出力しています。
https://storage.googleapis.com/zenn-user-upload/xxxxxxxxxxxxxxxxx
```

**Comment by catnose99** [comment]
あ、そういうことですか。
対応したいIssueがかなり溜まっているので、ちょっと特定の会社のイントラネットのPolicyを理由に対応することは難しいです。すみません。
