### ISSUE TITLE
コードブロックのレイアウトが崩れる(Firefox on Android 11)

### ISSUE THREAD

**Issue by yuwata** [zenn-dev/zenn-roadmap#94]
Android 11上のFirefoxで記事を読むと、コードブロックのレイアウトが崩れてしまいます。Chromeだと大丈夫です。
以下にスクリーンショットを上げておきます。

- Firefox
![Screenshot_20200928-235447](https://user-images.githubusercontent.com/14157143/94448990-86c38b00-01e6-11eb-8813-6f3e03a35750.png)

- Chrome
![Screenshot_20200928-235338](https://user-images.githubusercontent.com/14157143/94448981-84f9c780-01e6-11eb-879b-39edb9351af6.png)

**Comment by catnose99** [comment]
確認してみます。

**Comment by catnose99** [comment]
こちらさきほどzenn.devおよびzenn-cliにて修正しました。
@yuwata
可能でしたら修正されているかご確認いただけますでしょうか？

**Comment by yuwata** [comment]
修正されていること確認できました。
ありがとうございます。

**Comment by catnose99** [comment]
ありがとうございます！
