### ISSUE TITLE
トピックの用語に-や_を設定できるようにしてほしい

### ISSUE THREAD

**Issue by fagai** [zenn-dev/zenn-roadmap#96]
ちょうど`docker-compose`に関しての記事を書こうと思った際に`-`が使えないことに気づきました。
もし、こういう意図でこうしてますみたいなものがあったらすみません。

**Comment by catnose99** [comment]
記事読みました。とてもわかり易かったです。

下記リンク先のような事情があり泣く泣くそのような仕様にしています。
https://github.com/zenn-dev/zenn-roadmap/issues/35
ただ、そのまま表示を変えられないのは問題であるため、トピック作成後にトピックページから表示名を変更できるようにしています。
（ただ、荒らしを防ぐために現状申請制にしています。いろいろと面倒ですみません）
docker-composeについてはさきほど表示名を変えておきました。

**Comment by fagai** [comment]
なるほど。表記揺れの問題解決のためなんですね。
承知しました。

あと記事の感想ありがとうございます！
