### ISSUE TITLE
一部環境でコードブロックが等幅フォントで表示されません

### ISSUE THREAD

**Issue by kou029w** [zenn-dev/zenn-roadmap#99]
スクリーンショット:
![Image from Gyazo](https://i.gyazo.com/6ed795e28067786669e6b5239f753b7a.png)
OS: Ubuntu 20.04 LTS Desktop
ブラウザー: Google Chrome 85.0.4183.121（Official Build） （64 ビット）

表題の通りです。
記事を閲覧しているとコードブロックが等幅フォントで表示されません。
DevToolsでfont-familyを見るといくつか有名な等幅フォントが指定されている様子なので、おそらく意図していない振る舞いと考えます。

```
font-family: Menlo,Monaco,Consolas,Meiryo,Inter,monospace,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji
```

monospace が選択されれば問題なく等幅フォントで表示されるのですがプロポーショナルフォントであるInterが優先されているようです。

多くの環境では問題ない(と考える)のであまり重要な問題ではないかもしれませんが、すみませんがご確認のほどよろしくお願い申し上げます :bow:

**Comment by catnose99** [comment]
@kou029w 
原因まで考察いただき、ありがとうございます。
（おかげさまで修正点がすぐに分かりました！）

こちらさきほどzenn.devおよびzenn-cliにて修正しました。
zenn-cliを使っている場合はお手数ですが、`npm install zenn-cli@latest`の実行をお願いします。
